/**
 * Concept registry — Backend and Web Dev courses.
 *
 * A concept is a named primitive that questions exercise. SRS state lives on
 * (concept, user) so mastery propagates across topic boundaries: solving an
 * advanced card credits all the primitives it touches, and easy cards keyed
 * to those primitives get longer intervals automatically.
 *
 * Sizing target: 5–20 questions per concept once tagging is complete.
 * Per KLI / DataShop literature, that's the band where learning curves are
 * smooth enough to validate concept granularity. See CONCEPT_LAYER_SPEC.md.
 *
 * Authoring rules:
 *  - Concept ids are kebab-case, prefixed by area:
 *      Backend: py-, dj-, ce-, inf-
 *      Web Dev: web-, js-, ts-, react-, next-, prisma-, forms-, testing-,
 *               a11y-, shadcn-, pattern-, api-, db-
 *  - prereqs are SPARSE. Only encode an edge when you'd bet on it. Edges are
 *    advisory (used for unlock gating later); mastery transfer comes from
 *    shared concept tags, not from the prereq graph.
 *  - beta is the PFA difficulty offset for the concept. Default 0; raise for
 *    concepts that are inherently harder than average so the mastery score
 *    doesn't graduate them too cheaply.
 */
export type ConceptId = string;

export interface Concept {
  id: ConceptId;
  label: string;
  /** Section name (BACKEND_SECTIONS key) this concept primarily belongs to. */
  section: string;
  prereqs?: ConceptId[];
  /** PFA difficulty offset. Default 0. Negative = easy concept, positive = hard. */
  beta?: number;
}

export const BACKEND_CONCEPTS: Concept[] = [
  // ── Python core: data model & control flow ───────────────────────────────
  { id: 'py-mutable-vs-immutable', label: 'Mutable vs immutable types',
    section: 'Python Fundamentals' },
  { id: 'py-list-aliasing', label: 'List aliasing & shared references',
    section: 'Python Fundamentals', prereqs: ['py-mutable-vs-immutable'] },
  { id: 'py-mutable-default-arg', label: 'Mutable default arguments',
    section: 'Python Fundamentals', prereqs: ['py-list-aliasing'], beta: 0.3 },
  { id: 'py-is-vs-equals', label: '`is` vs `==` (identity vs equality)',
    section: 'Python Fundamentals' },
  { id: 'py-truthiness', label: 'Truthiness of values',
    section: 'Python Fundamentals' },
  { id: 'py-dict-key-hashability', label: 'Dict key hashability',
    section: 'Python Fundamentals' },
  { id: 'py-set-uniqueness', label: 'Set uniqueness & hashing',
    section: 'Python Fundamentals' },
  { id: 'py-unpacking', label: 'Tuple/iterable unpacking & starred targets',
    section: 'Python Fundamentals' },
  { id: 'py-range-bounds', label: 'range() bounds (off-by-one)',
    section: 'Python Fundamentals' },
  { id: 'py-slice-bounds', label: 'Slice bounds (start inclusive, stop exclusive)',
    section: 'Python Fundamentals' },
  { id: 'py-iterator-protocol', label: 'Iterator protocol (__iter__, __next__)',
    section: 'Python Fundamentals' },
  { id: 'py-loop-else', label: 'for/while-else clause semantics',
    section: 'Python Fundamentals' },
  { id: 'py-comprehension', label: 'List/dict/set comprehensions',
    section: 'Python Fundamentals', prereqs: ['py-iterator-protocol'] },
  { id: 'py-generator-yield', label: 'Generator functions & yield',
    section: 'Python Advanced', prereqs: ['py-iterator-protocol'], beta: 0.2 },

  // ── Python functions ──────────────────────────────────────────────────────
  { id: 'py-function-as-value', label: 'Functions as first-class values',
    section: 'Python Fundamentals' },
  { id: 'py-closure-capture', label: 'Closures & late-binding capture',
    section: 'Python Fundamentals', prereqs: ['py-function-as-value'], beta: 0.3 },
  { id: 'py-decorator-application', label: 'Decorator application & wrapping',
    section: 'Python Fundamentals', prereqs: ['py-closure-capture'], beta: 0.4 },
  { id: 'py-args-kwargs', label: '*args / **kwargs forwarding',
    section: 'Python Fundamentals' },
  { id: 'py-default-arg-evaluation', label: 'Default argument evaluation timing',
    section: 'Python Fundamentals', prereqs: ['py-mutable-default-arg'] },

  // ── Python OOP ────────────────────────────────────────────────────────────
  { id: 'py-class-instance-distinction', label: 'Class vs instance attributes & __init__/__new__',
    section: 'Python Fundamentals' },
  { id: 'py-super-call', label: 'super() and cooperative inheritance',
    section: 'Python Fundamentals', prereqs: ['py-class-instance-distinction'], beta: 0.3 },
  { id: 'py-mro-resolution', label: 'Method resolution order (C3 linearization)',
    section: 'Python Fundamentals', prereqs: ['py-super-call'], beta: 0.5 },
  { id: 'py-magic-methods', label: 'Dunder protocol methods',
    section: 'Python Advanced' },
  { id: 'py-abstract-method', label: 'ABCs and @abstractmethod',
    section: 'Python Advanced', prereqs: ['py-class-instance-distinction'] },
  { id: 'py-dataclass-defaults', label: 'Dataclass field defaults & default_factory',
    section: 'Python Advanced', prereqs: ['py-mutable-default-arg'] },

  // ── Python errors & context management ────────────────────────────────────
  { id: 'py-exception-hierarchy', label: 'Exception hierarchy & except ordering',
    section: 'Python Fundamentals' },
  { id: 'py-try-finally-ordering', label: 'try/except/else/finally ordering',
    section: 'Python Fundamentals' },
  { id: 'py-context-manager-protocol', label: 'Context manager protocol (__enter__/__exit__)',
    section: 'Python Advanced' },
  { id: 'py-raise-vs-reraise', label: 'raise vs raise from (chaining)',
    section: 'Python Fundamentals' },

  // ── Python concurrency ────────────────────────────────────────────────────
  { id: 'py-gil-implication', label: 'GIL implications for threading vs processing',
    section: 'Python Advanced', beta: 0.3 },
  { id: 'py-async-coroutines', label: 'async/await coroutine semantics',
    section: 'Python Advanced', beta: 0.4 },
  { id: 'py-event-loop', label: 'Event loop scheduling & blocking calls',
    section: 'Python Advanced', prereqs: ['py-async-coroutines'], beta: 0.4 },
  { id: 'py-thread-vs-process', label: 'Thread vs process tradeoffs (CPU vs IO)',
    section: 'Python Advanced', prereqs: ['py-gil-implication'] },

  // ── Python typing & validation ────────────────────────────────────────────
  { id: 'py-type-hint-syntax', label: 'PEP 585 / PEP 604 type hint syntax',
    section: 'Python Advanced' },
  { id: 'py-pydantic-validation', label: 'Pydantic validation & coercion',
    section: 'Python Advanced', prereqs: ['py-type-hint-syntax'] },

  // ── Django ORM & request flow ─────────────────────────────────────────────
  { id: 'dj-orm-query-construction', label: 'QuerySet construction & laziness',
    section: 'Django' },
  { id: 'dj-n-plus-one', label: 'N+1 query problem',
    section: 'Django', prereqs: ['dj-orm-query-construction'], beta: 0.3 },
  { id: 'dj-select-related-vs-prefetch', label: 'select_related vs prefetch_related',
    section: 'Django', prereqs: ['dj-n-plus-one'], beta: 0.4 },
  { id: 'dj-migration-dependency', label: 'Migration dependencies & ordering',
    section: 'Django' },
  { id: 'dj-middleware-ordering', label: 'Middleware ordering (request vs response)',
    section: 'Django Advanced & Deployment' },
  { id: 'dj-model-manager-vs-queryset', label: 'Custom Manager vs QuerySet methods',
    section: 'DRF Production Patterns' },
  { id: 'dj-transaction-atomic', label: 'transaction.atomic & nested savepoints',
    section: 'Django Advanced & Deployment' },
  { id: 'dj-signal-vs-override', label: 'Signals vs save()-override tradeoffs',
    section: 'Django Advanced & Deployment' },

  // ── Django REST Framework ─────────────────────────────────────────────────
  { id: 'dj-serializer-validation', label: 'Serializer field vs object-level validation',
    section: 'Django' },
  { id: 'dj-permission-class', label: 'Permission classes & object-level perms',
    section: 'Django' },
  { id: 'dj-auth-token-vs-session', label: 'Token auth vs session auth tradeoffs',
    section: 'Django' },
  { id: 'dj-pagination-strategy', label: 'Pagination: offset vs cursor vs page-number',
    section: 'DRF Production Patterns' },

  // ── Celery & background tasks ─────────────────────────────────────────────
  { id: 'ce-task-idempotency', label: 'Task idempotency & at-least-once delivery',
    section: 'Celery & Background Tasks', beta: 0.3 },
  { id: 'ce-chord-vs-chain', label: 'Chord vs chain vs group composition',
    section: 'Celery & Background Tasks', beta: 0.3 },
  { id: 'ce-worker-prefetch', label: 'Worker prefetch multiplier & long tasks',
    section: 'Celery & Background Tasks' },
  { id: 'ce-result-backend', label: 'Result backend tradeoffs & expiration',
    section: 'Celery & Background Tasks' },

  // ── Production infrastructure & security ──────────────────────────────────
  { id: 'inf-wsgi-vs-asgi', label: 'WSGI vs ASGI server models',
    section: 'Production Infrastructure' },
  { id: 'inf-connection-pooling', label: 'DB connection pooling & exhaustion',
    section: 'Production Infrastructure', beta: 0.2 },
  { id: 'inf-password-hashing', label: 'Password hashing (bcrypt/argon2 vs SHA)',
    section: 'Production Infrastructure' },

  // ── Standard-library deep dives ───────────────────────────────────────────
  { id: 'py-regex-syntax', label: 'Regex pattern syntax & capture groups',
    section: 'Python Advanced' },
  { id: 'py-itertools-combinators', label: 'itertools combinators (chain, groupby, takewhile)',
    section: 'Python Advanced', prereqs: ['py-iterator-protocol'] },
  { id: 'py-functools-cache-partial', label: 'functools (lru_cache, partial, reduce, wraps)',
    section: 'Python Advanced', prereqs: ['py-decorator-application'] },
  { id: 'py-collections-stdlib', label: 'collections (Counter, defaultdict, deque, namedtuple)',
    section: 'Python Advanced' },
  { id: 'py-modern-syntax', label: 'Modern Python syntax (match/case, walrus, PEP 604 unions)',
    section: 'Python Mastery & Advanced' },
  { id: 'py-security-primitives', label: 'Security primitives (hmac, secrets, constant-time compare)',
    section: 'Python Advanced', beta: 0.2 },
  { id: 'py-logging-config', label: 'Logging config (handlers, levels, propagation)',
    section: 'Python Advanced' },
  { id: 'py-json-serialization', label: 'JSON serialization & custom encoders',
    section: 'Python Advanced' },
  { id: 'py-test-isolation', label: 'Test isolation (mocks, fixtures, parametrize)',
    section: 'Python Advanced', beta: 0.2 },
  { id: 'py-modules-imports', label: 'Module imports (absolute vs relative, __init__.py, __main__)',
    section: 'Python Fundamentals' },

  // ── Django depth (concepts beyond the high-level ORM/request flow) ────────
  { id: 'dj-view-patterns', label: 'View patterns (FBV vs CBV, generic views, mixins)',
    section: 'Django' },
  { id: 'dj-form-validation', label: 'Form validation & ModelForm cleaning',
    section: 'Django' },
  { id: 'dj-model-construction', label: 'Model fields, choices, related_name, on_delete',
    section: 'Django' },
  { id: 'dj-admin', label: 'Django admin customization (ModelAdmin, list_display, inlines, actions)',
    section: 'Django' },
  { id: 'dj-api-docs', label: 'DRF API documentation (drf-spectacular, OpenAPI, Swagger)',
    section: 'DRF Production Patterns' },
  { id: 'dj-caching', label: 'Django caching (cache_page, low-level cache, Redis)',
    section: 'Django Advanced & Deployment', beta: 0.2 },
  { id: 'dj-deployment-cicd', label: 'Django deployment & CI/CD (Docker, gunicorn, GitHub Actions, static files)',
    section: 'Django Advanced & Deployment' },
  { id: 'dj-management-commands', label: 'Custom management commands (BaseCommand, manage.py)',
    section: 'Django Advanced & Deployment' },
  { id: 'dj-channels-realtime', label: 'Django Channels (WebSockets, SSE, real-time)',
    section: 'Django Advanced & Deployment', beta: 0.3 },
  { id: 'dj-storage-backends', label: 'Storage backends (S3, django-storages, media handling)',
    section: 'Django Advanced & Deployment' },
  { id: 'dj-test-fixtures', label: 'Test data factories (factory_boy, Faker)',
    section: 'DRF Production Patterns' },
  { id: 'py-string-formatting', label: 'String formatting (f-strings, .format, interpolation)',
    section: 'Python Fundamentals' },
  { id: 'py-cli-tools', label: 'CLI tools (argparse, click, subcommands)',
    section: 'Python Advanced' },
  { id: 'dj-templates', label: 'Django Template Language (tags, filters, inheritance)',
    section: 'Django' },
  { id: 'dj-setup', label: 'Django project/app setup (startproject, startapp, INSTALLED_APPS)',
    section: 'Django' },
  { id: 'dj-service-layer', label: 'Service layer (thin views, fat services, separation of concerns)',
    section: 'Django Advanced & Deployment' },
  { id: 'dj-monitoring', label: 'Production monitoring (Sentry, error tracking, structured logging)',
    section: 'Django Advanced & Deployment' },
  { id: 'inf-postgres', label: 'Postgres features & tuning (jsonb, full-text search, EXPLAIN, indexes, VACUUM)',
    section: 'Production Infrastructure', beta: 0.3 },
  { id: 'dj-http-cycle', label: 'HTTP request/response cycle, MVC/MVT, status codes, cookies/sessions',
    section: 'Django' },
  { id: 'py-control-flow', label: 'Control flow (if/elif/else, loops, break/continue)',
    section: 'Python Fundamentals' },
  { id: 'py-arithmetic-ops', label: 'Arithmetic operators (//, %, **, math precedence)',
    section: 'Python Fundamentals' },
  { id: 'py-builtin-io', label: 'Built-in I/O & types (print, input, int/float/str/bool, type casting)',
    section: 'Python Fundamentals' },
  { id: 'py-datetime-handling', label: 'datetime, timedelta, timezone (zoneinfo, strftime/strptime, isoformat)',
    section: 'Python Advanced' },
  { id: 'py-pathlib', label: 'pathlib paths (joinpath, with_suffix, read_text/write_text)',
    section: 'Python Advanced' },
  { id: 'py-file-io-modes', label: 'File I/O (open modes, read/write/seek, readline vs readlines)',
    section: 'Python Fundamentals' },
  { id: 'py-pickle-serialization', label: 'pickle serialization (dumps/loads, __getstate__/__setstate__)',
    section: 'Python Advanced' },
  { id: 'py-shell-os-interop', label: 'Shell & OS interop (subprocess, shutil, tempfile, os.environ)',
    section: 'Python Advanced' },
  { id: 'py-packaging-tools', label: 'Packaging (venv, pyproject.toml, pip editable installs, lockfiles)',
    section: 'Python Advanced' },
  { id: 'py-runtime', label: 'Python runtime (CPython, interpreter vs compiler, bytecode)',
    section: 'Python Fundamentals' },
  { id: 'py-metaclass', label: 'Metaclasses (type, __new__, class introspection, dynamic creation)',
    section: 'Python Mastery & Advanced', beta: 0.4 },
];

/** Map of concept id → Concept for O(1) lookup. */
export const BACKEND_CONCEPT_MAP: Record<ConceptId, Concept> = Object.fromEntries(
  BACKEND_CONCEPTS.map(c => [c.id, c])
);

/**
 * Hint mapping from existing free-form `tags` array values to concept ids.
 * Used by scripts/bootstrap-concept-tags.ts for first-pass auto-assignment.
 * High-confidence only — ambiguous tags are deliberately left unmapped so the
 * QA pass surfaces them.
 */
export const TAG_TO_CONCEPTS: Record<string, ConceptId[]> = {
  // Python core
  'mutable': ['py-mutable-vs-immutable'],
  'mutability': ['py-mutable-vs-immutable'],
  'aliasing': ['py-list-aliasing'],
  'mutable-default': ['py-mutable-default-arg'],
  'default-args': ['py-default-arg-evaluation'],
  'identity': ['py-is-vs-equals'],
  'truthiness': ['py-truthiness'],
  'unpacking': ['py-unpacking'],
  'slicing': ['py-slice-bounds'],
  'range': ['py-range-bounds'],
  'iterator': ['py-iterator-protocol'],
  'iter': ['py-iterator-protocol'],
  'comprehension': ['py-comprehension'],
  'comprehensions': ['py-comprehension'],
  'list-comprehension': ['py-comprehension'],
  'dict-comprehension': ['py-comprehension'],
  'generator': ['py-generator-yield'],
  'yield': ['py-generator-yield'],

  // Functions
  'closures': ['py-closure-capture'],
  'closure': ['py-closure-capture'],
  'decorator': ['py-decorator-application'],
  'decorators': ['py-decorator-application'],
  'args-kwargs': ['py-args-kwargs'],
  'first-class': ['py-function-as-value'],

  // OOP
  'oop': ['py-class-instance-distinction'],
  'classes': ['py-class-instance-distinction'],
  'inheritance': ['py-super-call'],
  'super': ['py-super-call'],
  'mro': ['py-mro-resolution'],
  'magic-methods': ['py-magic-methods'],
  'dunder': ['py-magic-methods'],
  'abc': ['py-abstract-method'],
  'abstract': ['py-abstract-method'],
  'dataclass': ['py-dataclass-defaults'],
  'dataclasses': ['py-dataclass-defaults'],

  // Errors & context
  'exception': ['py-exception-hierarchy'],
  'exceptions': ['py-exception-hierarchy'],
  'try-except': ['py-try-finally-ordering'],
  'finally': ['py-try-finally-ordering'],
  'context-manager': ['py-context-manager-protocol'],
  'with-statement': ['py-context-manager-protocol'],
  'raise-from': ['py-raise-vs-reraise'],

  // Concurrency
  'gil': ['py-gil-implication'],
  'async': ['py-async-coroutines'],
  'await': ['py-async-coroutines'],
  'asyncio': ['py-async-coroutines', 'py-event-loop'],
  'event-loop': ['py-event-loop'],
  'threading': ['py-thread-vs-process'],
  'multiprocessing': ['py-thread-vs-process'],

  // Typing
  'type-hints': ['py-type-hint-syntax'],
  'typing': ['py-type-hint-syntax'],
  'pydantic': ['py-pydantic-validation'],

  // Django
  'queryset': ['dj-orm-query-construction'],
  'orm': ['dj-orm-query-construction'],
  'n+1': ['dj-n-plus-one'],
  'n-plus-one': ['dj-n-plus-one'],
  'select-related': ['dj-select-related-vs-prefetch'],
  'select_related': ['dj-select-related-vs-prefetch'],
  'prefetch-related': ['dj-select-related-vs-prefetch'],
  'prefetch_related': ['dj-select-related-vs-prefetch'],
  'auth': ['dj-auth-token-vs-session'],
  'filter': ['dj-orm-query-construction'],
  'transactions': ['dj-transaction-atomic'],
  'migration': ['dj-migration-dependency'],
  'migrations': ['dj-migration-dependency'],
  'middleware': ['dj-middleware-ordering'],
  'manager': ['dj-model-manager-vs-queryset'],
  'transaction': ['dj-transaction-atomic'],
  'atomic': ['dj-transaction-atomic'],
  'signals': ['dj-signal-vs-override'],
  'serializer': ['dj-serializer-validation'],
  'serializers': ['dj-serializer-validation'],
  'permissions': ['dj-permission-class'],
  'authentication': ['dj-auth-token-vs-session'],
  'pagination': ['dj-pagination-strategy'],

  // Celery
  'celery': ['ce-task-idempotency'],
  'idempotency': ['ce-task-idempotency'],
  'chord': ['ce-chord-vs-chain'],
  'chain': ['ce-chord-vs-chain'],
  'prefetch': ['ce-worker-prefetch'],

  // Infra
  'wsgi': ['inf-wsgi-vs-asgi'],
  'asgi': ['inf-wsgi-vs-asgi'],
  'connection-pool': ['inf-connection-pooling'],
  'bcrypt': ['inf-password-hashing'],
  'argon2': ['inf-password-hashing'],

  // Stdlib deep dives
  'regex': ['py-regex-syntax'],
  're': ['py-regex-syntax'],
  'itertools': ['py-itertools-combinators'],
  'functools': ['py-functools-cache-partial'],
  'lru-cache': ['py-functools-cache-partial'],
  'partial': ['py-functools-cache-partial'],
  'reduce': ['py-functools-cache-partial'],
  'collections': ['py-collections-stdlib'],
  'counter': ['py-collections-stdlib'],
  'defaultdict': ['py-collections-stdlib'],
  'deque': ['py-collections-stdlib'],
  'namedtuple': ['py-collections-stdlib'],
  'modern': ['py-modern-syntax'],
  'match-case': ['py-modern-syntax'],
  'walrus': ['py-modern-syntax'],
  'security': ['py-security-primitives'],
  'hmac': ['py-security-primitives'],
  'secrets': ['py-security-primitives'],
  'logging': ['py-logging-config'],
  'json': ['py-json-serialization'],
  'serialization': ['py-json-serialization'],
  'testing': ['py-test-isolation'],
  'mock': ['py-test-isolation'],
  'mocks': ['py-test-isolation'],
  'pytest': ['py-test-isolation'],
  'fixtures': ['py-test-isolation'],
  'parametrize': ['py-test-isolation'],
  'modules': ['py-modules-imports'],
  'imports': ['py-modules-imports'],
  '__init__': ['py-modules-imports'],

  // Mapping gaps for existing concepts (these tags already had a concept;
  // the bootstrap diagnostic surfaced them as unmapped).
  'error-handling': ['py-exception-hierarchy'],
  'dict': ['py-dict-key-hashability'],
  'lists': ['py-list-aliasing'],

  // Django depth
  'views': ['dj-view-patterns'],
  'view': ['dj-view-patterns'],
  'cbv': ['dj-view-patterns'],
  'fbv': ['dj-view-patterns'],
  'urls': ['dj-view-patterns'],
  'forms': ['dj-form-validation'],
  'modelform': ['dj-form-validation'],
  'models': ['dj-model-construction'],
  'on-delete': ['dj-model-construction'],
  'jsonfield': ['dj-model-construction'],

  // Concurrency depth (covered by py-thread-vs-process beyond the basics)
  'concurrency': ['py-thread-vs-process'],
  'event': ['py-thread-vs-process'],
  'rlock': ['py-thread-vs-process'],
  'lock': ['py-thread-vs-process'],
  'semaphore': ['py-thread-vs-process'],

  // Functools further
  'lru_cache': ['py-functools-cache-partial'],
  'memoization': ['py-functools-cache-partial'],

  // Sets & truthiness gaps surfaced by LOW pass
  'set': ['py-set-uniqueness'],
  'intersection': ['py-set-uniqueness'],
  'union': ['py-set-uniqueness'],
  'boolean': ['py-truthiness'],
  'falsy': ['py-truthiness'],
  'truthy': ['py-truthiness'],
  'keyword-only': ['py-args-kwargs'],
  'positional-only': ['py-args-kwargs'],

  // Django admin
  'admin': ['dj-admin'],
  'modeladmin': ['dj-admin'],
  'model-admin': ['dj-admin'],
  'list_display': ['dj-admin'],
  'tabularinline': ['dj-admin'],
  'tabular-inline': ['dj-admin'],
  'inline': ['dj-admin'],
  'register': ['dj-admin'],
  'admin-action': ['dj-admin'],
  'fieldsets': ['dj-admin'],
  'readonly_fields': ['dj-admin'],
  'bulk-operations': ['dj-admin'],
  'bulk': ['dj-admin'],
  'actions': ['dj-admin'],

  // DRF API documentation
  'api-docs': ['dj-api-docs'],
  'api-documentation': ['dj-api-docs'],
  'openapi': ['dj-api-docs'],
  'swagger': ['dj-api-docs'],
  'redoc': ['dj-api-docs'],
  'drf-spectacular': ['dj-api-docs'],
  'extend_schema': ['dj-api-docs'],

  // Django caching
  'caching': ['dj-caching'],
  'cache_page': ['dj-caching'],
  'cache.get': ['dj-caching'],
  'cache': ['dj-caching'],

  // Django deployment & CI/CD
  'cicd': ['dj-deployment-cicd'],
  'ci-cd': ['dj-deployment-cicd'],
  'ci': ['dj-deployment-cicd'],
  'cd': ['dj-deployment-cicd'],
  'github-actions': ['dj-deployment-cicd'],
  'devops': ['dj-deployment-cicd'],
  'deployment': ['dj-deployment-cicd'],
  'docker': ['dj-deployment-cicd'],
  'docker-compose': ['dj-deployment-cicd'],
  'dockerfile': ['dj-deployment-cicd'],
  'gunicorn': ['dj-deployment-cicd'],
  'static-files': ['dj-deployment-cicd'],
  'whitenoise': ['dj-deployment-cicd'],
  'collectstatic': ['dj-deployment-cicd'],
  '12-factor': ['dj-deployment-cicd'],

  // Django management commands
  'management-command': ['dj-management-commands'],
  'management-commands': ['dj-management-commands'],
  'basecommand': ['dj-management-commands'],
  'manage-py': ['dj-management-commands'],

  // Django Channels
  'channels': ['dj-channels-realtime'],
  'websocket': ['dj-channels-realtime'],
  'websockets': ['dj-channels-realtime'],
  'sse': ['dj-channels-realtime'],
  'real-time': ['dj-channels-realtime'],
  'channel-layer': ['dj-channels-realtime'],
  'long-polling': ['dj-channels-realtime'],

  // Django storage backends
  's3': ['dj-storage-backends'],
  'django-storages': ['dj-storage-backends'],
  'storage-backend': ['dj-storage-backends'],
  'media': ['dj-storage-backends'],

  // Test fixtures
  'factory_boy': ['dj-test-fixtures'],
  'factory-boy': ['dj-test-fixtures'],
  'faker': ['dj-test-fixtures'],
  'subfactory': ['dj-test-fixtures'],
  'create_batch': ['dj-test-fixtures'],

  // String formatting
  'fstring': ['py-string-formatting'],
  'f-string': ['py-string-formatting'],
  'f-strings': ['py-string-formatting'],
  'interpolation': ['py-string-formatting'],
  'format-string': ['py-string-formatting'],
  '.format': ['py-string-formatting'],
  'strings': ['py-string-formatting'],

  // CLI tooling
  'cli': ['py-cli-tools'],
  'argparse': ['py-cli-tools'],
  'subcommands': ['py-cli-tools'],
  'click': ['py-cli-tools'],

  // Django templates
  'template': ['dj-templates'],
  'templates': ['dj-templates'],
  'truncate': ['dj-templates'],
  'date': ['dj-templates'],

  // Django project setup
  'setup': ['dj-setup'],
  'startproject': ['dj-setup'],
  'startapp': ['dj-setup'],
  'installed_apps': ['dj-setup'],
  'installed-apps': ['dj-setup'],
  'appconfig': ['dj-setup'],
  'manage.py': ['dj-setup'],
  'project-setup': ['dj-setup'],

  // Service layer
  'service-layer': ['dj-service-layer'],
  'thin-models': ['dj-service-layer'],
  'fat-models': ['dj-service-layer'],
  'separation-of-concerns': ['dj-service-layer'],

  // Monitoring
  'monitoring': ['dj-monitoring'],
  'error-tracking': ['dj-monitoring'],
  'sentry': ['dj-monitoring'],
  'observability': ['dj-monitoring'],

  // Postgres features & tuning
  'postgres': ['inf-postgres'],
  'postgresql': ['inf-postgres'],
  'jsonb': ['inf-postgres'],
  'full-text-search': ['inf-postgres'],
  'searchrank': ['inf-postgres'],
  'searchvector': ['inf-postgres'],
  'search-rank': ['inf-postgres'],
  'search-vector': ['inf-postgres'],
  'analyze': ['inf-postgres'],
  'explain': ['inf-postgres'],
  'vacuum': ['inf-postgres'],
  'query-planner': ['inf-postgres'],
  'index': ['inf-postgres'],
  'sqlite': ['inf-postgres'],
  'data-modeling': ['inf-postgres'],

  // DRF views & routers — fold into existing dj-view-patterns
  'apiview': ['dj-view-patterns'],
  'viewset': ['dj-view-patterns'],
  'modelviewset': ['dj-view-patterns'],
  'generic-views': ['dj-view-patterns'],
  'defaultrouter': ['dj-view-patterns'],
  'router': ['dj-view-patterns'],
  'listcreateapiview': ['dj-view-patterns'],
  'perform_create': ['dj-view-patterns'],
  'get_queryset': ['dj-view-patterns'],
  'basepermission': ['dj-permission-class'],

  // DRF serializers — fold into existing dj-serializer-validation
  'modelserializer': ['dj-serializer-validation'],
  'nested-serializer': ['dj-serializer-validation'],
  'validate_field': ['dj-serializer-validation'],
  'validationerror': ['dj-serializer-validation'],
  'serializermethodfield': ['dj-serializer-validation'],
  'serializer.data': ['dj-serializer-validation'],

  // Model fields & meta
  'model': ['dj-model-construction'],
  'meta': ['dj-model-construction'],
  'foreignkey': ['dj-model-construction'],
  'relationship': ['dj-model-construction'],
  'ordering': ['dj-model-construction'],

  // Django filtering / queryset extras
  'django-filter': ['dj-orm-query-construction'],
  'filtering': ['dj-orm-query-construction'],
  'bulk-create': ['dj-orm-query-construction'],

  // Form depth
  'clean': ['dj-form-validation'],
  'csrf': ['dj-form-validation'],

  // HTTP fundamentals
  'mvc': ['dj-http-cycle'],
  'mvt': ['dj-http-cycle'],
  'request-response': ['dj-http-cycle'],
  'request': ['dj-http-cycle'],
  'http': ['dj-http-cycle'],
  'status-codes': ['dj-http-cycle'],
  'sessions': ['dj-http-cycle'],
  'cookies': ['dj-http-cycle'],
  'stateless': ['dj-http-cycle'],
  'cycle': ['dj-http-cycle'],

  // Control flow
  'control-flow': ['py-control-flow'],
  'conditional': ['py-control-flow'],
  'conditionals': ['py-control-flow'],
  'comparison': ['py-control-flow'],
  'if': ['py-control-flow'],
  'elif': ['py-control-flow'],
  'else': ['py-control-flow'],
  'loops': ['py-control-flow'],
  'while': ['py-control-flow'],
  'for-loop': ['py-control-flow'],
  'break': ['py-control-flow'],
  'continue': ['py-control-flow'],
  'iteration': ['py-control-flow'],
  'enumerate': ['py-control-flow'],
  'zip': ['py-control-flow'],
  'logical-operators': ['py-control-flow'],
  'and': ['py-control-flow'],
  'membership': ['py-control-flow'],
  'in': ['py-control-flow'],

  // Arithmetic
  'arithmetic': ['py-arithmetic-ops'],
  'operators': ['py-arithmetic-ops'],
  'modulo': ['py-arithmetic-ops'],
  'exponentiation': ['py-arithmetic-ops'],
  'floor-division': ['py-arithmetic-ops'],
  'division': ['py-arithmetic-ops'],
  'remainder': ['py-arithmetic-ops'],
  'power': ['py-arithmetic-ops'],
  'equality': ['py-arithmetic-ops'],

  // I/O & primitive types
  'print': ['py-builtin-io'],
  'output': ['py-builtin-io'],
  'input': ['py-builtin-io'],
  'user-input': ['py-builtin-io'],
  'hello-world': ['py-builtin-io'],
  'casting': ['py-builtin-io'],
  'type-conversion': ['py-builtin-io'],
  'data-types': ['py-builtin-io'],
  'bool': ['py-builtin-io'],
  'int': ['py-builtin-io'],
  'float': ['py-builtin-io'],
  'str': ['py-builtin-io'],
  'dynamic-typing': ['py-builtin-io'],
  'assignment': ['py-builtin-io'],
  'variables': ['py-builtin-io'],

  // Default args
  'default-arguments': ['py-default-arg-evaluation'],
  'return': ['py-function-as-value'],

  // Cache extras
  'cache-aside': ['dj-caching'],
  'django-cache': ['dj-caching'],
  'django-redis': ['dj-caching'],
  'redis': ['dj-caching'],

  // Lambdas / scope / OOP basics
  'lambda': ['py-function-as-value'],
  'nonlocal': ['py-closure-capture'],
  'scope': ['py-closure-capture'],
  'legb': ['py-closure-capture'],
  'global': ['py-closure-capture'],
  'def': ['py-function-as-value'],
  'parameters': ['py-args-kwargs'],
  'arguments': ['py-args-kwargs'],
  'default-parameters': ['py-default-arg-evaluation'],
  'default-params': ['py-default-arg-evaluation'],
  'defaults': ['py-default-arg-evaluation'],
  'keyword-args': ['py-args-kwargs'],
  'kwargs': ['py-args-kwargs'],
  'instance': ['py-class-instance-distinction'],
  'method': ['py-class-instance-distinction'],
  'self': ['py-class-instance-distinction'],
  'init': ['py-class-instance-distinction'],
  'attribute': ['py-class-instance-distinction'],
  'class': ['py-class-instance-distinction'],

  // Copy semantics → list aliasing concept (covers reference/copy depth)
  'copy': ['py-list-aliasing'],
  'deep-copy': ['py-list-aliasing'],
  'deepcopy': ['py-list-aliasing'],
  'shallow-copy': ['py-list-aliasing'],
  'copy-module': ['py-list-aliasing'],
  'nested-lists': ['py-list-aliasing'],
  'references': ['py-list-aliasing'],

  // Metaclasses / metaprogramming
  'metaclass': ['py-metaclass'],
  'metaprogramming': ['py-metaclass'],
  '__new__': ['py-metaclass'],
  'type': ['py-metaclass'],
  'dynamic-class': ['py-metaclass'],
  'class-creation': ['py-metaclass'],
  'introspection': ['py-metaclass'],

  // Dictionary operations
  'dict-merge': ['py-dict-key-hashability'],
  'key-value': ['py-dict-key-hashability'],
  'keys': ['py-dict-key-hashability'],
  'values': ['py-dict-key-hashability'],
  'keyerror': ['py-dict-key-hashability'],
  'dictionaries': ['py-dict-key-hashability'],

  // List/tuple primitives
  'tuple': ['py-mutable-vs-immutable'],
  'mutable-content': ['py-mutable-vs-immutable'],
  'list': ['py-list-aliasing'],
  'append': ['py-list-aliasing'],
  'extend': ['py-list-aliasing'],

  // Sorting
  'sorted': ['py-iterator-protocol'],
  'sorting': ['py-iterator-protocol'],
  'reverse': ['py-iterator-protocol'],
  'sort': ['py-iterator-protocol'],
  'attrgetter': ['py-itertools-combinators'],
  'itemgetter': ['py-itertools-combinators'],
  'operator': ['py-itertools-combinators'],

  // Datetime
  'datetime': ['py-datetime-handling'],
  'timedelta': ['py-datetime-handling'],
  'timezone': ['py-datetime-handling'],
  'zoneinfo': ['py-datetime-handling'],
  'fromisoformat': ['py-datetime-handling'],
  'isoformat': ['py-datetime-handling'],
  'astimezone': ['py-datetime-handling'],
  'strftime': ['py-datetime-handling'],
  'strptime': ['py-datetime-handling'],
  'leap-year': ['py-datetime-handling'],
  'utc': ['py-datetime-handling'],
  'total_seconds': ['py-datetime-handling'],

  // pathlib
  'pathlib': ['py-pathlib'],
  'path': ['py-pathlib'],
  'paths': ['py-pathlib'],
  'joinpath': ['py-pathlib'],
  'with_suffix': ['py-pathlib'],
  'read_text': ['py-pathlib'],
  'write_text': ['py-pathlib'],
  'directory': ['py-pathlib'],

  // File I/O modes
  'file': ['py-file-io-modes'],
  'file-io': ['py-file-io-modes'],
  'read': ['py-file-io-modes'],
  'write': ['py-file-io-modes'],
  'readline': ['py-file-io-modes'],
  'readlines': ['py-file-io-modes'],
  'writelines': ['py-file-io-modes'],
  'open': ['py-file-io-modes'],
  'modes': ['py-file-io-modes'],
  'seek': ['py-file-io-modes'],
  'cursor': ['py-file-io-modes'],
  'eof': ['py-file-io-modes'],
  'append-mode': ['py-file-io-modes'],
  'csv': ['py-file-io-modes'],
  'dictreader': ['py-file-io-modes'],

  // Try/except depth
  'try': ['py-exception-hierarchy'],
  'except': ['py-exception-hierarchy'],
  'as': ['py-exception-hierarchy'],
  'value-error': ['py-exception-hierarchy'],
  'exception-object': ['py-exception-hierarchy'],

  // Pickle
  'pickle': ['py-pickle-serialization'],
  'dumps': ['py-pickle-serialization'],
  'loads': ['py-pickle-serialization'],
  'persistence': ['py-pickle-serialization'],
  'getstate': ['py-pickle-serialization'],
  'setstate': ['py-pickle-serialization'],
  'serialisation': ['py-pickle-serialization'],

  // Shell / OS
  'subprocess': ['py-shell-os-interop'],
  'run': ['py-shell-os-interop'],
  'capture_output': ['py-shell-os-interop'],
  'tempfile': ['py-shell-os-interop'],
  'temporarydirectory': ['py-shell-os-interop'],
  'shutil': ['py-shell-os-interop'],
  'disk_usage': ['py-shell-os-interop'],
  'filesystem': ['py-shell-os-interop'],
  'os': ['py-shell-os-interop'],
  'environ': ['py-shell-os-interop'],
  'env-vars': ['py-shell-os-interop'],

  // Security primitives — extra tag forms
  'hashing': ['py-security-primitives'],
  'hashlib': ['py-security-primitives'],
  'sha256': ['py-security-primitives'],
  'uuid': ['py-security-primitives'],
  'base64': ['py-security-primitives'],
  'binary': ['py-security-primitives'],
  'encoding': ['py-security-primitives'],
  'identifiers': ['py-security-primitives'],

  // Runtime
  'compilation': ['py-runtime'],
  'interpreter': ['py-runtime'],
  'cpython': ['py-runtime'],
  'implementations': ['py-runtime'],
  'how-python-works': ['py-runtime'],

  // Packaging
  'packaging': ['py-packaging-tools'],
  'venv': ['py-packaging-tools'],
  'virtualenv': ['py-packaging-tools'],
  'pyproject': ['py-packaging-tools'],
  'pep-621': ['py-packaging-tools'],
  'editable-install': ['py-packaging-tools'],
  'pip': ['py-packaging-tools'],
  'lockfile': ['py-packaging-tools'],

  // Modern Python
  'enum': ['py-modern-syntax'],
  'pattern-matching': ['py-modern-syntax'],

  // SQL / aggregation in backend questions
  'sql': ['dj-orm-query-construction'],
  'aggregation': ['dj-orm-query-construction'],
  'group-by': ['dj-orm-query-construction'],
  'join': ['dj-orm-query-construction'],
  'create-table': ['dj-orm-query-construction'],
  'constraints': ['dj-model-construction'],

  // Django app concept
  'app': ['dj-setup'],

  // DRF/Django project residuals
  'blog-api': ['dj-view-patterns'],
  'action': ['dj-view-patterns'],
  'microservices': ['dj-service-layer'],
  'monolith': ['dj-service-layer'],

  // Python syntax basics
  'keywords': ['py-function-as-value'],
  'indentation': ['py-control-flow'],
  'blocks': ['py-control-flow'],
  'syntax': ['py-control-flow'],

  // Context managers
  'contextlib': ['py-context-manager-protocol'],
  'exitstack': ['py-context-manager-protocol'],
  'context-managers': ['py-context-manager-protocol'],
  'with': ['py-context-manager-protocol'],
  'resources': ['py-context-manager-protocol'],
  'try-finally': ['py-try-finally-ordering'],
};

// ─────────────────────────────────────────────────────────────────────────────
// Web Dev course
// ─────────────────────────────────────────────────────────────────────────────

export const WEBDEV_CONCEPTS: Concept[] = [
  // ── HTML, CSS & Tailwind ──────────────────────────────────────────────────
  { id: 'web-html-semantics', label: 'Semantic HTML elements & document outline',
    section: 'HTML, CSS & Tailwind' },
  { id: 'web-html-forms-a11y', label: 'HTML form inputs, labels & validation attributes',
    section: 'HTML, CSS & Tailwind' },
  { id: 'web-html-link-security', label: 'target="_blank" + rel="noopener noreferrer"',
    section: 'HTML, CSS & Tailwind' },
  { id: 'web-css-specificity', label: 'CSS selector specificity & cascade',
    section: 'HTML, CSS & Tailwind', beta: 0.2 },
  { id: 'web-css-box-model', label: 'Box model & box-sizing',
    section: 'HTML, CSS & Tailwind' },
  { id: 'web-css-flexbox', label: 'Flexbox direction, alignment & wrap',
    section: 'HTML, CSS & Tailwind' },
  { id: 'web-css-grid', label: 'CSS Grid (template areas, fr units, auto placement)',
    section: 'HTML, CSS & Tailwind', beta: 0.2 },
  { id: 'web-css-responsive', label: 'Media queries & mobile-first responsive design',
    section: 'HTML, CSS & Tailwind' },
  { id: 'web-tailwind-utility', label: 'Tailwind utility composition & responsive prefixes',
    section: 'HTML, CSS & Tailwind' },
  { id: 'web-css-animation', label: 'CSS transitions, animations & keyframes',
    section: 'HTML, CSS & Tailwind' },
  { id: 'web-git-workflow', label: 'Git basics (add, commit, push, branches, stash)',
    section: 'HTML, CSS & Tailwind' },

  // ── JavaScript Fundamentals ───────────────────────────────────────────────
  { id: 'js-var-let-const', label: 'var/let/const, hoisting & TDZ',
    section: 'JavaScript Fundamentals' },
  { id: 'js-equality-coercion', label: '== vs === and type coercion',
    section: 'JavaScript Fundamentals' },
  { id: 'js-this-binding', label: 'this binding rules (default/implicit/explicit/new/arrow)',
    section: 'JavaScript Fundamentals', beta: 0.4 },
  { id: 'js-closures', label: 'Closures & lexical scope',
    section: 'JavaScript Fundamentals', beta: 0.3 },
  { id: 'js-array-methods', label: 'Array methods (map/filter/reduce/find)',
    section: 'JavaScript Fundamentals' },
  { id: 'js-spread-destructuring', label: 'Spread/rest & object/array destructuring',
    section: 'JavaScript Fundamentals' },
  { id: 'js-promises-async', label: 'Promises & async/await',
    section: 'JavaScript Fundamentals', beta: 0.3 },
  { id: 'js-event-loop', label: 'Event loop, micro vs macrotasks',
    section: 'JavaScript Fundamentals', prereqs: ['js-promises-async'], beta: 0.4 },
  { id: 'js-prototype-chain', label: 'Prototype chain & __proto__',
    section: 'JavaScript Fundamentals', beta: 0.3 },
  { id: 'js-object-mutation', label: 'Reference equality & object mutation',
    section: 'JavaScript Fundamentals' },
  { id: 'js-dom-events', label: 'DOM manipulation & event handling',
    section: 'JavaScript Fundamentals' },
  { id: 'js-error-handling', label: 'try/catch, error propagation & rejection',
    section: 'JavaScript Fundamentals', prereqs: ['js-promises-async'] },

  // ── React ─────────────────────────────────────────────────────────────────
  { id: 'react-state-immutability', label: 'State immutability & batched updates',
    section: 'React' },
  { id: 'react-effect-deps', label: 'useEffect dependency array & infinite loops',
    section: 'React', beta: 0.4 },
  { id: 'react-effect-cleanup', label: 'useEffect cleanup functions',
    section: 'React', prereqs: ['react-effect-deps'], beta: 0.3 },
  { id: 'react-controlled-forms', label: 'Controlled vs uncontrolled inputs',
    section: 'React' },
  { id: 'react-key-prop', label: 'List keys & reconciliation',
    section: 'React' },
  { id: 'react-context', label: 'Context propagation & re-render impact',
    section: 'React', beta: 0.3 },
  { id: 'react-memoization', label: 'memo, useMemo, useCallback',
    section: 'React', beta: 0.4 },
  { id: 'react-custom-hooks', label: 'Custom hook composition',
    section: 'React' },
  { id: 'react-ref-imperative', label: 'useRef vs state for imperative values',
    section: 'React' },
  { id: 'react-conditional-rendering', label: 'JSX conditional rendering patterns',
    section: 'React' },

  // ── TypeScript ────────────────────────────────────────────────────────────
  { id: 'ts-structural-typing', label: 'Structural type compatibility',
    section: 'TypeScript' },
  { id: 'ts-type-vs-interface', label: 'Type alias vs interface tradeoffs',
    section: 'TypeScript' },
  { id: 'ts-generics', label: 'Generic functions & type parameters with constraints',
    section: 'TypeScript', beta: 0.4 },
  { id: 'ts-narrowing', label: 'Type narrowing (typeof, in, instanceof, predicates)',
    section: 'TypeScript', beta: 0.3 },
  { id: 'ts-utility-types', label: 'Utility types (Partial, Pick, Omit, Record)',
    section: 'TypeScript' },
  { id: 'ts-discriminated-unions', label: 'Discriminated unions & exhaustive narrowing',
    section: 'TypeScript', prereqs: ['ts-narrowing'], beta: 0.3 },
  { id: 'ts-any-vs-unknown', label: 'any vs unknown vs never',
    section: 'TypeScript' },
  { id: 'ts-void-never', label: 'void vs never return types',
    section: 'TypeScript' },
  { id: 'ts-null-safety', label: 'strictNullChecks & optional chaining',
    section: 'TypeScript' },

  // ── Next.js ───────────────────────────────────────────────────────────────
  { id: 'next-server-vs-client', label: '"use client" boundary & component placement',
    section: 'Next.js', beta: 0.3 },
  { id: 'next-app-router', label: 'App Router (layouts, dynamic segments, params)',
    section: 'Next.js' },
  { id: 'next-data-fetching', label: 'fetch caching, revalidation & dynamic rendering',
    section: 'Next.js', beta: 0.3 },
  { id: 'next-server-actions', label: 'Server Actions for mutations',
    section: 'Next.js', beta: 0.3 },
  { id: 'next-route-handlers', label: 'API route handlers (route.ts)',
    section: 'Next.js' },
  { id: 'next-middleware', label: 'Middleware execution & auth gating',
    section: 'Next.js' },
  { id: 'next-hydration', label: 'Hydration mismatch & client/server divergence',
    section: 'Next.js', prereqs: ['next-server-vs-client'], beta: 0.4 },
  { id: 'next-streaming-suspense', label: 'Streaming, Suspense & loading.tsx',
    section: 'Next.js', beta: 0.3 },
  { id: 'next-deployment', label: 'Deployment (standalone, static export, Docker, self-hosting)',
    section: 'Next.js' },

  // ── Prisma & Database ─────────────────────────────────────────────────────
  { id: 'prisma-schema-relations', label: 'Prisma schema, models & @relation',
    section: 'Prisma & Database' },
  { id: 'prisma-include-select', label: 'Prisma include vs select & N+1',
    section: 'Prisma & Database', beta: 0.3 },
  { id: 'prisma-migrations', label: 'prisma migrate dev vs deploy',
    section: 'Prisma & Database' },

  // ── Forms & Validation (RHF + Zod) ────────────────────────────────────────
  { id: 'forms-rhf-controller', label: 'React Hook Form Controller for controlled libs',
    section: 'Forms & Validation (RHF + Zod)' },
  { id: 'forms-zod-schema', label: 'Zod schema construction & inference',
    section: 'Forms & Validation (RHF + Zod)' },
  { id: 'forms-zod-resolver', label: 'zodResolver + RHF integration',
    section: 'Forms & Validation (RHF + Zod)' },

  // ── Testing ───────────────────────────────────────────────────────────────
  { id: 'testing-rtl-queries', label: 'RTL query priorities (getByRole etc.)',
    section: 'Testing' },
  { id: 'testing-user-event', label: 'userEvent vs fireEvent',
    section: 'Testing' },
  { id: 'testing-async', label: 'waitFor / findBy async patterns',
    section: 'Testing', beta: 0.2 },
  { id: 'testing-msw-mocking', label: 'MSW for fetch mocking',
    section: 'Testing', beta: 0.2 },

  // ── Advanced Next.js Patterns ─────────────────────────────────────────────
  { id: 'next-tanstack-query', label: 'TanStack Query: queryKey & invalidation',
    section: 'Advanced Next.js Patterns', beta: 0.3 },
  { id: 'next-url-state', label: 'URL as state (searchParams, useSearchParams)',
    section: 'Advanced Next.js Patterns' },
  { id: 'next-error-boundary', label: 'error.tsx & error boundaries',
    section: 'Advanced Next.js Patterns' },

  // ── Accessibility ─────────────────────────────────────────────────────────
  { id: 'a11y-aria-roles', label: 'ARIA roles & semantic-first preference',
    section: 'Accessibility' },
  { id: 'a11y-keyboard-nav', label: 'Keyboard navigation & focus management',
    section: 'Accessibility' },
  { id: 'a11y-form-labels', label: 'Form label association & accessible names',
    section: 'Accessibility' },

  // ── UI Libraries & Advanced Styling ───────────────────────────────────────
  { id: 'shadcn-radix-primitives', label: 'Radix primitives composition',
    section: 'UI Libraries & Advanced Styling' },
  { id: 'shadcn-cn-utility', label: 'cn() / clsx + tailwind-merge',
    section: 'UI Libraries & Advanced Styling' },

  // ── Design Patterns & Architecture ────────────────────────────────────────
  { id: 'pattern-creational', label: 'Creational patterns (Factory, Singleton, Builder)',
    section: 'Design Patterns & Architecture' },
  { id: 'pattern-structural', label: 'Structural patterns (Adapter, Decorator, Facade)',
    section: 'Design Patterns & Architecture' },
  { id: 'pattern-behavioral', label: 'Behavioral patterns (Observer, Strategy, Command)',
    section: 'Design Patterns & Architecture' },
  { id: 'pattern-architectural', label: 'Architectural patterns (MVC, MVVM, Clean Architecture)',
    section: 'Design Patterns & Architecture', beta: 0.2 },
  { id: 'api-rest-conventions', label: 'REST verbs, status codes & resource design',
    section: 'Design Patterns & Architecture' },
  { id: 'api-pagination', label: 'Pagination strategies (offset vs cursor)',
    section: 'Design Patterns & Architecture' },
  { id: 'db-normalization', label: 'Database normalization (1NF/2NF/3NF) tradeoffs',
    section: 'Design Patterns & Architecture' },
  { id: 'db-indexing', label: 'Index types & cardinality',
    section: 'Design Patterns & Architecture', beta: 0.2 },
  { id: 'web-security-xss', label: 'XSS prevention (escaping, CSP)',
    section: 'Design Patterns & Architecture', beta: 0.3 },
  { id: 'web-security-csrf', label: 'CSRF tokens & SameSite cookies',
    section: 'Design Patterns & Architecture', beta: 0.3 },
  { id: 'web-security-cors', label: 'CORS, preflight & credentials',
    section: 'Design Patterns & Architecture', beta: 0.3 },
  { id: 'web-security-auth-tokens', label: 'JWT vs session auth & refresh tokens',
    section: 'Design Patterns & Architecture', beta: 0.3 },
  { id: 'web-security-input-validation', label: 'Input validation & output encoding',
    section: 'Design Patterns & Architecture' },
];

/** Map of concept id → Concept for O(1) lookup. */
export const WEBDEV_CONCEPT_MAP: Record<ConceptId, Concept> = Object.fromEntries(
  WEBDEV_CONCEPTS.map(c => [c.id, c])
);

/**
 * Web-dev tag→concept map. Kept separate from TAG_TO_CONCEPTS so generic tag
 * names (`closure`, `async`, `inheritance`) don't collide with backend
 * concepts. The bootstrap script reads the right map based on --course=...
 */
export const WEBDEV_TAG_TO_CONCEPTS: Record<string, ConceptId[]> = {
  // HTML / CSS / Tailwind
  'semantic': ['web-html-semantics'],
  'semantic-html': ['web-html-semantics'],
  'html': ['web-html-semantics'],
  'seo': ['web-html-semantics'],
  'forms': ['web-html-forms-a11y'],
  'form': ['web-html-forms-a11y'],
  'input': ['web-html-forms-a11y'],
  'link': ['web-html-link-security'],
  'anchor': ['web-html-link-security'],
  'noopener': ['web-html-link-security'],
  'specificity': ['web-css-specificity'],
  'cascade': ['web-css-specificity'],
  'box-model': ['web-css-box-model'],
  'box-sizing': ['web-css-box-model'],
  'flexbox': ['web-css-flexbox'],
  'flex': ['web-css-flexbox'],
  'centering': ['web-css-flexbox'],
  'grid': ['web-css-grid'],
  'css-grid': ['web-css-grid'],
  'columns': ['web-css-grid'],
  'responsive': ['web-css-responsive'],
  'media-query': ['web-css-responsive'],
  'mobile-first': ['web-css-responsive'],
  'tailwind': ['web-tailwind-utility'],

  // JavaScript fundamentals
  'let': ['js-var-let-const'],
  'const': ['js-var-let-const'],
  'var': ['js-var-let-const'],
  'hoisting': ['js-var-let-const'],
  'tdz': ['js-var-let-const'],
  'variables': ['js-var-let-const'],
  'equality': ['js-equality-coercion'],
  'coercion': ['js-equality-coercion'],
  'type-coercion': ['js-equality-coercion'],
  'this': ['js-this-binding'],
  'arrow': ['js-this-binding'],
  'arrow-function': ['js-this-binding'],
  'closure': ['js-closures'],
  'closures': ['js-closures'],
  'scope': ['js-closures'],
  'lexical-scope': ['js-closures'],
  'array': ['js-array-methods'],
  'arrays': ['js-array-methods'],
  'map': ['js-array-methods'],
  'filter': ['js-array-methods'],
  'reduce': ['js-array-methods'],
  'find': ['js-array-methods'],
  'spread': ['js-spread-destructuring'],
  'rest-params': ['js-spread-destructuring'],
  'destructuring': ['js-spread-destructuring'],
  'merge': ['js-spread-destructuring'],
  'promise': ['js-promises-async'],
  'promises': ['js-promises-async'],
  'async': ['js-promises-async'],
  'await': ['js-promises-async'],
  'async-await': ['js-promises-async'],
  'fetch': ['js-promises-async'],
  'promise-all': ['js-promises-async'],
  'event-loop': ['js-event-loop'],
  'microtask': ['js-event-loop'],
  'macrotask': ['js-event-loop'],
  'prototype': ['js-prototype-chain'],
  'prototype-chain': ['js-prototype-chain'],
  'inheritance': ['js-prototype-chain'],
  'mutation': ['js-object-mutation'],
  'reference': ['js-object-mutation'],
  'immutable': ['js-object-mutation'],
  'objects': ['js-object-mutation'],
  'dom': ['js-dom-events'],
  'events': ['js-dom-events'],
  'event-delegation': ['js-dom-events'],
  'textcontent': ['js-dom-events'],
  'localstorage': ['js-dom-events'],
  'error-handling': ['js-error-handling'],
  'try-catch': ['js-error-handling'],
  'throw': ['js-error-handling'],
  'rejection': ['js-error-handling'],

  // React
  'usestate': ['react-state-immutability'],
  'state': ['react-state-immutability'],
  'setstate': ['react-state-immutability'],
  'useeffect': ['react-effect-deps'],
  'effect': ['react-effect-deps'],
  'cleanup': ['react-effect-cleanup'],
  'unmount': ['react-effect-cleanup'],
  'controlled': ['react-controlled-forms'],
  'uncontrolled': ['react-controlled-forms'],
  'key': ['react-key-prop'],
  'keys': ['react-key-prop'],
  'reconciliation': ['react-key-prop'],
  'context': ['react-context'],
  'usecontext': ['react-context'],
  'createcontext': ['react-context'],
  'provider': ['react-context'],
  'usememo': ['react-memoization'],
  'usecallback': ['react-memoization'],
  'react.memo': ['react-memoization'],
  'memoization': ['react-memoization'],
  'custom-hook': ['react-custom-hooks'],
  'custom-hooks': ['react-custom-hooks'],
  'useref': ['react-ref-imperative'],
  'ref': ['react-ref-imperative'],
  'usereducer': ['react-state-immutability'],

  // TypeScript
  'structural-typing': ['ts-structural-typing'],
  'interface': ['ts-type-vs-interface'],
  'interfaces': ['ts-type-vs-interface'],
  'type-alias': ['ts-type-vs-interface'],
  'generics': ['ts-generics'],
  'generic': ['ts-generics'],
  'narrowing': ['ts-narrowing'],
  'type-guard': ['ts-narrowing'],
  'type-predicate': ['ts-narrowing'],
  'typeof': ['ts-narrowing'],
  'utility-types': ['ts-utility-types'],
  'partial': ['ts-utility-types'],
  'pick': ['ts-utility-types'],
  'omit': ['ts-utility-types'],
  'record': ['ts-utility-types'],
  'discriminated-union': ['ts-discriminated-unions'],
  'discriminated': ['ts-discriminated-unions'],
  'unknown': ['ts-any-vs-unknown'],
  'any': ['ts-any-vs-unknown'],
  'never': ['ts-any-vs-unknown'],

  // Next.js
  'use-client': ['next-server-vs-client'],
  'server-component': ['next-server-vs-client'],
  'server-components': ['next-server-vs-client'],
  'client-component': ['next-server-vs-client'],
  'client-components': ['next-server-vs-client'],
  'app-router': ['next-app-router'],
  'routing': ['next-app-router'],
  'layouts': ['next-app-router'],
  'data-fetching': ['next-data-fetching'],
  'caching': ['next-data-fetching'],
  'revalidation': ['next-data-fetching'],
  'revalidate': ['next-data-fetching'],
  'dynamic': ['next-data-fetching'],
  'server-actions': ['next-server-actions'],
  'route-handler': ['next-route-handlers'],
  'route-handlers': ['next-route-handlers'],
  'middleware': ['next-middleware'],
  'hydration': ['next-hydration'],
  'ssr': ['next-hydration'],
  'streaming': ['next-streaming-suspense'],
  'suspense': ['next-streaming-suspense'],
  'loading': ['next-streaming-suspense'],

  // Prisma — keep tags specific; 'schema' alone is ambiguous with Zod schemas.
  'prisma': ['prisma-schema-relations'],
  'prisma-schema': ['prisma-schema-relations'],
  'relations': ['prisma-schema-relations'],
  'nested-relations': ['prisma-schema-relations'],
  'findmany': ['prisma-schema-relations'],
  'include': ['prisma-include-select'],

  // Forms & Validation
  'react-hook-form': ['forms-rhf-controller'],
  'rhf': ['forms-rhf-controller'],
  'controller': ['forms-rhf-controller'],
  'zod': ['forms-zod-schema'],
  'zodresolver': ['forms-zod-resolver'],
  'safeparse': ['forms-zod-schema'],
  'validation': ['forms-zod-schema'],

  // Testing — 'queries' is ambiguous (Prisma/RTL); rely on RTL-specific tags.
  'react-testing-library': ['testing-rtl-queries'],
  'rtl': ['testing-rtl-queries'],
  'rtl-queries': ['testing-rtl-queries'],
  'getbyrole': ['testing-rtl-queries'],
  'user-event': ['testing-user-event'],
  'userevent': ['testing-user-event'],
  'fireevent': ['testing-user-event'],
  'waitfor': ['testing-async'],
  'findby': ['testing-async'],
  'msw': ['testing-msw-mocking'],
  'mock-service-worker': ['testing-msw-mocking'],
  'api-mocking': ['testing-msw-mocking'],
  'jest': ['testing-rtl-queries'],

  // Advanced Next.js
  'tanstack-query': ['next-tanstack-query'],
  'tanstack': ['next-tanstack-query'],
  'react-query': ['next-tanstack-query'],
  'querykey': ['next-tanstack-query'],
  'url-state': ['next-url-state'],
  'searchparams': ['next-url-state'],
  'usesearchparams': ['next-url-state'],
  'error-boundary': ['next-error-boundary'],
  'error.tsx': ['next-error-boundary'],

  // Accessibility
  'accessibility': ['a11y-aria-roles'],
  'aria': ['a11y-aria-roles'],
  'wcag': ['a11y-aria-roles'],
  'roles': ['a11y-aria-roles'],
  'keyboard': ['a11y-keyboard-nav'],
  'focus': ['a11y-keyboard-nav'],
  'tab-order': ['a11y-keyboard-nav'],
  'label': ['a11y-form-labels'],
  'labels': ['a11y-form-labels'],
  'accessible-name': ['a11y-form-labels'],

  // shadcn / Radix
  'shadcn': ['shadcn-radix-primitives'],
  'radix': ['shadcn-radix-primitives'],
  'cn': ['shadcn-cn-utility'],
  'clsx': ['shadcn-cn-utility'],
  'tailwind-merge': ['shadcn-cn-utility'],

  // Patterns & architecture
  'creational': ['pattern-creational'],
  'factory': ['pattern-creational'],
  'singleton': ['pattern-creational'],
  'builder': ['pattern-creational'],
  'structural': ['pattern-structural'],
  'adapter': ['pattern-structural'],
  'decorator': ['pattern-structural'],
  'facade': ['pattern-structural'],
  'behavioral': ['pattern-behavioral'],
  'observer': ['pattern-behavioral'],
  'strategy': ['pattern-behavioral'],
  'command': ['pattern-behavioral'],
  'pub-sub': ['pattern-behavioral'],
  'architectural': ['pattern-architectural'],
  'mvc': ['pattern-architectural'],
  'mvvm': ['pattern-architectural'],
  'clean-architecture': ['pattern-architectural'],
  'architecture': ['pattern-architectural'],

  // API & DB
  'rest': ['api-rest-conventions'],
  'api-design': ['api-rest-conventions'],
  'status-codes': ['api-rest-conventions'],
  'pagination': ['api-pagination'],
  'cursor-pagination': ['api-pagination'],
  'normalization': ['db-normalization'],
  'database-design': ['db-normalization'],
  'indexing': ['db-indexing'],
  'index': ['db-indexing'],

  // Security
  'xss': ['web-security-xss'],
  'csp': ['web-security-xss'],
  'csrf': ['web-security-csrf'],
  'samesite': ['web-security-csrf'],
  'cors': ['web-security-cors'],
  'preflight': ['web-security-cors'],
  'jwt': ['web-security-auth-tokens'],
  'session': ['web-security-auth-tokens'],
  'refresh-token': ['web-security-auth-tokens'],
  'authentication': ['web-security-auth-tokens'],
  'auth': ['web-security-auth-tokens'],
  'next-auth': ['web-security-auth-tokens'],
  'authorization': ['web-security-auth-tokens'],
  'rbac': ['web-security-auth-tokens'],
  'cookies': ['web-security-csrf'],
  'sanitization': ['web-security-input-validation'],
  'input-validation': ['web-security-input-validation'],
  'security': ['web-security-input-validation'],

  // ── LOW-pass cleanup additions ────────────────────────────────────────────

  // Object inspection methods → object mutation/reference concept
  'object.keys': ['js-object-mutation'],
  'object.values': ['js-object-mutation'],
  'object.entries': ['js-object-mutation'],
  'object-keys': ['js-object-mutation'],
  'object-values': ['js-object-mutation'],
  'object-entries': ['js-object-mutation'],

  // Equality / coercion neighbours
  'nullish-coalescing': ['js-equality-coercion'],
  'optional-chaining': ['js-equality-coercion'],
  'logical-or': ['js-equality-coercion'],
  'falsy': ['js-equality-coercion'],
  'truthy': ['js-equality-coercion'],
  'nan': ['js-equality-coercion'],
  'comparison': ['js-equality-coercion'],
  'conditional': ['js-equality-coercion'],
  'es2020': ['js-equality-coercion'],

  // CSS box / styling
  'box-shadow': ['web-css-box-model'],
  'styling': ['web-css-box-model'],
  'card': ['web-css-box-model'],

  // CSS animation
  'animation': ['web-css-animation'],
  'transition': ['web-css-animation'],
  'keyframes': ['web-css-animation'],
  'fadein': ['web-css-animation'],
  'hover': ['web-css-animation'],

  // Git workflow
  'git': ['web-git-workflow'],
  'commit': ['web-git-workflow'],
  'push': ['web-git-workflow'],
  'stash': ['web-git-workflow'],
  'branch': ['web-git-workflow'],
  'workflow': ['web-git-workflow'],

  // Testing extras
  'e2e': ['testing-async'],
  'playwright': ['testing-async'],
  'unit': ['testing-rtl-queries'],
  'integration': ['testing-rtl-queries'],
  'integration-tests': ['testing-rtl-queries'],
  'testing-strategy': ['testing-rtl-queries'],
  'testing-trophy': ['testing-rtl-queries'],

  // Next.js routing extras
  'dynamic-routes': ['next-app-router'],
  'params': ['next-app-router'],
  'state-reset': ['next-app-router'],
  'client-side-navigation': ['next-app-router'],
  'next/link': ['next-app-router'],
  'prefetching': ['next-app-router'],

  // Next.js server boundary extras
  'async-component': ['next-data-fetching'],
  'build-error': ['next-server-vs-client'],
  'node-apis': ['next-server-vs-client'],
  'server-client-boundary': ['next-server-vs-client'],
  'serialization': ['next-server-vs-client'],

  // Next.js form/action state
  'form-validation': ['forms-zod-schema'],
  'pending-state': ['next-server-actions'],
  'useactionstate': ['next-server-actions'],
  'useformstatus': ['next-server-actions'],

  // Next.js deployment
  'deployment': ['next-deployment'],
  'server-vs-static': ['next-deployment'],
  'standalone': ['next-deployment'],
  'static-export': ['next-deployment'],
  'docker': ['next-deployment'],
  'self-hosting': ['next-deployment'],

  // DB indexing extras
  'b-tree': ['db-indexing'],
  'covering-index': ['db-indexing'],
  'database-performance': ['db-indexing'],
  'indexes': ['db-indexing'],

  // Next.js rendering modes — ISR/static-generation are caching/revalidation patterns
  'isr': ['next-data-fetching'],
  'static-generation': ['next-data-fetching'],
  'rendering': ['next-data-fetching'],

  // React perf primitives that flag perf concerns
  'usedeferredvalue': ['react-memoization'],
  'usetransition': ['react-memoization'],

  // Security headers (HSTS, CSP, X-Frame-Options, clickjacking) → folded into XSS concept
  'security-headers': ['web-security-xss'],
  'hsts': ['web-security-xss'],
  'x-frame-options': ['web-security-xss'],
  'clickjacking': ['web-security-xss'],

  // Template literal — ES6 feature, treated as variable/syntax primitive
  'template-literal': ['js-var-let-const'],

  // Cross-course residuals (webdev questions referencing Django/DB patterns)
  'n-plus-one': ['db-indexing'],
  'select-related': ['db-indexing'],
  'orm': ['db-indexing'],
  'database': ['db-indexing'],

  // TS basic types fallback — type primitives / function types
  'types': ['ts-any-vs-unknown'],
  'optional': ['ts-any-vs-unknown'],
  'default-params': ['ts-any-vs-unknown'],
};

/**
 * Databricks course concepts — Spark/PySpark, Spark SQL, Delta Lake, Structured
 * Streaming, DLT, Unity Catalog, dimensional modeling. Section names match
 * DATABRICKS_SECTIONS in courseConfig.ts.
 *
 * Prefixes:
 *   dbx-    Databricks platform & utilities
 *   ps-     PySpark / DataFrame API
 *   sql-    Spark SQL surface
 *   delta-  Delta Lake table operations
 *   stream- Structured Streaming
 *   dlt-    Delta Live Tables
 *   ucat-   Unity Catalog & governance
 *   dim-    Dimensional modeling & warehousing
 */
export const DATABRICKS_CONCEPTS: Concept[] = [
  // ── Lakehouse Platform ───────────────────────────────────────────────────
  { id: 'dbx-architecture', label: 'Spark + Databricks architecture (driver, workers)',
    section: 'Lakehouse Platform' },
  { id: 'dbx-cluster-config', label: 'Cluster configuration (all-purpose vs job, autoscaling, policies)',
    section: 'Lakehouse Platform' },
  { id: 'dbx-dbfs', label: 'DBFS & mount points',
    section: 'Lakehouse Platform' },
  { id: 'dbx-utilities', label: 'dbutils.fs / dbutils.notebook (file ops, exit, run)',
    section: 'Lakehouse Platform' },
  { id: 'dbx-secrets', label: 'dbutils.secrets & secret scopes',
    section: 'Lakehouse Platform' },
  { id: 'dbx-widgets', label: 'dbutils.widgets (parameterized notebooks)',
    section: 'Lakehouse Platform' },
  { id: 'dbx-repos', label: 'Databricks Repos & git integration',
    section: 'Lakehouse Platform' },
  { id: 'delta-acid', label: 'Delta Lake ACID transactions & table format',
    section: 'Lakehouse Platform' },
  { id: 'delta-merge', label: 'MERGE INTO upserts (when matched / not matched)',
    section: 'Lakehouse Platform', prereqs: ['delta-acid'], beta: 0.3 },
  { id: 'delta-clone', label: 'DEEP vs SHALLOW CLONE',
    section: 'Lakehouse Platform', prereqs: ['delta-acid'] },
  { id: 'delta-time-travel', label: 'Delta time travel (VERSION/TIMESTAMP AS OF, RESTORE)',
    section: 'Lakehouse Platform', prereqs: ['delta-acid'] },
  { id: 'delta-optimize', label: 'OPTIMIZE & file compaction',
    section: 'Lakehouse Platform', prereqs: ['delta-acid'] },
  { id: 'delta-zorder', label: 'Z-ORDER co-locating columns',
    section: 'Lakehouse Platform', prereqs: ['delta-optimize'], beta: 0.3 },
  { id: 'delta-vacuum', label: 'VACUUM & retention windows',
    section: 'Lakehouse Platform', prereqs: ['delta-acid'] },
  { id: 'delta-constraints', label: 'CHECK / NOT NULL constraints on Delta tables',
    section: 'Lakehouse Platform', prereqs: ['delta-acid'] },
  { id: 'delta-table-properties', label: 'TBLPROPERTIES & feature toggles',
    section: 'Lakehouse Platform', prereqs: ['delta-acid'] },

  // ── ELT with Spark SQL & Python ──────────────────────────────────────────
  { id: 'ps-session-init', label: 'SparkSession.builder & getOrCreate',
    section: 'ELT with Spark SQL & Python' },
  { id: 'ps-dataframe-create', label: 'createDataFrame, schema (StructType/StructField), printSchema',
    section: 'ELT with Spark SQL & Python', prereqs: ['ps-session-init'] },
  { id: 'ps-select-filter', label: 'select / filter / where column selection',
    section: 'ELT with Spark SQL & Python' },
  { id: 'ps-with-column', label: 'withColumn, withColumnRenamed, lit',
    section: 'ELT with Spark SQL & Python' },
  { id: 'ps-when-otherwise', label: 'when().otherwise() conditional logic',
    section: 'ELT with Spark SQL & Python' },
  { id: 'ps-cast-types', label: 'cast() / type conversions',
    section: 'ELT with Spark SQL & Python' },
  { id: 'ps-distinct-drop-dup', label: 'distinct / dropDuplicates',
    section: 'ELT with Spark SQL & Python' },
  { id: 'ps-orderby-sort', label: 'orderBy / sort & asc/desc',
    section: 'ELT with Spark SQL & Python' },
  { id: 'ps-groupby-agg', label: 'groupBy + agg / count / sum',
    section: 'ELT with Spark SQL & Python' },
  { id: 'ps-actions-vs-transforms', label: 'Transformations vs actions & lazy evaluation',
    section: 'ELT with Spark SQL & Python', beta: 0.2 },
  { id: 'ps-narrow-vs-wide', label: 'Narrow vs wide transformations',
    section: 'ELT with Spark SQL & Python', prereqs: ['ps-actions-vs-transforms'], beta: 0.3 },
  { id: 'ps-io-csv', label: 'CSV read/write with header & schema',
    section: 'ELT with Spark SQL & Python' },
  { id: 'ps-io-json', label: 'JSON read/write & corrupt-record handling',
    section: 'ELT with Spark SQL & Python' },
  { id: 'ps-io-parquet', label: 'Parquet columnar storage',
    section: 'ELT with Spark SQL & Python' },
  { id: 'ps-write-modes', label: 'Write modes (append, overwrite, error, ignore)',
    section: 'ELT with Spark SQL & Python' },
  { id: 'ps-string-fns', label: 'String functions (upper/lower/concat/concat_ws/trim/substring/split/length)',
    section: 'ELT with Spark SQL & Python' },
  { id: 'ps-regex-fns', label: 'regexp_extract / regexp_replace',
    section: 'ELT with Spark SQL & Python', prereqs: ['ps-string-fns'] },
  { id: 'ps-datetime-fns', label: 'Date/time functions (to_date, date_add, datediff, date_format)',
    section: 'ELT with Spark SQL & Python' },
  { id: 'ps-collection-fns', label: 'Array/map/struct functions (explode, array_contains, size, flatten)',
    section: 'ELT with Spark SQL & Python' },
  { id: 'ps-pivot-unpivot', label: 'pivot / stack / unpivot reshape',
    section: 'ELT with Spark SQL & Python', beta: 0.3 },
  { id: 'ps-math-fns', label: 'Math functions (round, abs, sqrt, pow, greatest)',
    section: 'ELT with Spark SQL & Python' },
  { id: 'ps-aggregate-fns', label: 'Aggregate functions (sum, avg, max, collect_list, collect_set, percentile)',
    section: 'ELT with Spark SQL & Python' },
  { id: 'ps-null-handling', label: 'fillna / coalesce / isNull / three-valued logic',
    section: 'ELT with Spark SQL & Python' },
  { id: 'ps-udf-pandas-udf', label: 'UDFs & vectorized pandas UDFs',
    section: 'ELT with Spark SQL & Python', beta: 0.4 },
  { id: 'sql-temp-views', label: 'createOrReplaceTempView & SQL bridge',
    section: 'ELT with Spark SQL & Python' },
  { id: 'sql-where-having', label: 'WHERE vs HAVING (filter before/after aggregation)',
    section: 'ELT with Spark SQL & Python', beta: 0.3 },
  { id: 'sql-subqueries', label: 'Subqueries (scalar / correlated / IN / EXISTS)',
    section: 'ELT with Spark SQL & Python', beta: 0.3 },
  { id: 'sql-cte', label: 'Common Table Expressions (WITH)',
    section: 'ELT with Spark SQL & Python' },
  { id: 'sql-case-expr', label: 'CASE WHEN expressions',
    section: 'ELT with Spark SQL & Python' },
  { id: 'sql-set-operations', label: 'UNION / UNION ALL / INTERSECT / EXCEPT',
    section: 'ELT with Spark SQL & Python' },
  { id: 'sql-joins-inner-outer', label: 'INNER / LEFT / RIGHT / FULL OUTER joins',
    section: 'ELT with Spark SQL & Python' },
  { id: 'sql-joins-semi-anti', label: 'LEFT SEMI / LEFT ANTI joins',
    section: 'ELT with Spark SQL & Python', prereqs: ['sql-joins-inner-outer'], beta: 0.3 },
  { id: 'sql-joins-cross-self', label: 'CROSS JOIN & self-joins',
    section: 'ELT with Spark SQL & Python', prereqs: ['sql-joins-inner-outer'] },
  { id: 'sql-window-ranking', label: 'Window ranking (row_number / rank / dense_rank / ntile / percent_rank)',
    section: 'ELT with Spark SQL & Python', beta: 0.3 },
  { id: 'sql-window-offset', label: 'Window offset (lag / lead / first / last)',
    section: 'ELT with Spark SQL & Python', prereqs: ['sql-window-ranking'] },
  { id: 'sql-window-frame', label: 'Window frames (ROWS BETWEEN / RANGE BETWEEN, running/cumulative)',
    section: 'ELT with Spark SQL & Python', prereqs: ['sql-window-ranking'], beta: 0.4 },
  { id: 'sql-grouping-rollup', label: 'ROLLUP / CUBE / GROUPING SETS',
    section: 'ELT with Spark SQL & Python', beta: 0.3 },

  // ── Incremental Data Processing ──────────────────────────────────────────
  { id: 'stream-readstream-writestream', label: 'readStream / writeStream basics',
    section: 'Incremental Data Processing', beta: 0.2 },
  { id: 'stream-triggers', label: 'Streaming triggers (default, processingTime, availableNow, continuous)',
    section: 'Incremental Data Processing', prereqs: ['stream-readstream-writestream'] },
  { id: 'stream-output-modes', label: 'Output modes (append / complete / update)',
    section: 'Incremental Data Processing', prereqs: ['stream-readstream-writestream'] },
  { id: 'stream-watermarks', label: 'Watermarks for late data & event-time bounds',
    section: 'Incremental Data Processing', prereqs: ['stream-readstream-writestream'], beta: 0.4 },
  { id: 'stream-checkpoint', label: 'Checkpointing & exactly-once recovery',
    section: 'Incremental Data Processing', prereqs: ['stream-readstream-writestream'], beta: 0.3 },
  { id: 'stream-stateful-aggs', label: 'Stateful streaming aggregations & state management',
    section: 'Incremental Data Processing', prereqs: ['stream-watermarks'], beta: 0.4 },
  { id: 'stream-stream-join', label: 'Stream-stream joins with watermarks & time bounds',
    section: 'Incremental Data Processing', prereqs: ['stream-watermarks'], beta: 0.5 },
  { id: 'stream-autoloader', label: 'Auto Loader (cloudFiles) & file detection',
    section: 'Incremental Data Processing' },
  { id: 'stream-schema-evolution', label: 'Schema inference & evolution in streaming',
    section: 'Incremental Data Processing', prereqs: ['stream-autoloader'], beta: 0.3 },
  { id: 'medallion-architecture', label: 'Bronze / silver / gold medallion layers',
    section: 'Incremental Data Processing' },
  { id: 'delta-cdf', label: 'Change Data Feed (table_changes, readChangeFeed)',
    section: 'Incremental Data Processing', prereqs: ['delta-acid'], beta: 0.3 },

  // ── Production Pipelines ─────────────────────────────────────────────────
  { id: 'dlt-pipeline-basics', label: 'DLT pipeline (@dlt.table, streaming vs materialized)',
    section: 'Production Pipelines', beta: 0.3 },
  { id: 'dlt-expectations', label: 'DLT expectations (expect / expect_or_drop / expect_or_fail)',
    section: 'Production Pipelines', prereqs: ['dlt-pipeline-basics'] },
  { id: 'dlt-pipeline-modes', label: 'DLT triggered vs continuous pipeline modes',
    section: 'Production Pipelines', prereqs: ['dlt-pipeline-basics'] },
  { id: 'dbx-workflows', label: 'Workflows / jobs orchestration (DAGs, tasks, retries, taskValues)',
    section: 'Production Pipelines', beta: 0.3 },

  // ── Optimization & Advanced ──────────────────────────────────────────────
  { id: 'ps-cache-persist', label: 'cache / persist / unpersist (storage levels)',
    section: 'Optimization & Advanced' },
  { id: 'ps-broadcast-join', label: 'Broadcast joins & broadcast hints',
    section: 'Optimization & Advanced', prereqs: ['sql-joins-inner-outer'], beta: 0.3 },
  { id: 'ps-shuffle', label: 'Shuffle, shuffle partitions, parallelism',
    section: 'Optimization & Advanced', prereqs: ['ps-narrow-vs-wide'], beta: 0.4 },
  { id: 'ps-partitioning', label: 'partitionBy / repartition / coalesce(n)',
    section: 'Optimization & Advanced', beta: 0.3 },
  { id: 'ps-aqe', label: 'Adaptive Query Execution & skew handling',
    section: 'Optimization & Advanced', beta: 0.4 },
  { id: 'ps-execution-plans', label: 'explain() / execution plans / predicate pushdown',
    section: 'Optimization & Advanced', beta: 0.4 },
  { id: 'ps-partition-pruning', label: 'Partition pruning & predicate pushdown',
    section: 'Optimization & Advanced', prereqs: ['ps-partitioning'] },

  // ── Data Governance ──────────────────────────────────────────────────────
  { id: 'ucat-namespaces', label: 'Three-level namespace (catalog.schema.table)',
    section: 'Data Governance' },
  { id: 'ucat-managed-vs-external', label: 'Managed vs external tables',
    section: 'Data Governance' },
  { id: 'ucat-grants', label: 'GRANT / REVOKE / SHOW GRANTS / privileges',
    section: 'Data Governance' },
  { id: 'ucat-lineage', label: 'Unity Catalog lineage & audit',
    section: 'Data Governance' },

  // ── Data Modeling & Warehousing Design ───────────────────────────────────
  { id: 'dim-star-schema', label: 'Star schema (fact + dimension tables)',
    section: 'Data Modeling & Warehousing Design' },
  { id: 'dim-snowflake-schema', label: 'Snowflake schema (normalized dimensions)',
    section: 'Data Modeling & Warehousing Design', prereqs: ['dim-star-schema'] },
  { id: 'dim-grain', label: 'Grain of a fact table',
    section: 'Data Modeling & Warehousing Design', prereqs: ['dim-star-schema'], beta: 0.3 },
  { id: 'dim-additivity', label: 'Additive / semi-additive / non-additive measures',
    section: 'Data Modeling & Warehousing Design', prereqs: ['dim-grain'], beta: 0.3 },
  { id: 'dim-conformed-dims', label: 'Conformed dimensions & bus matrix',
    section: 'Data Modeling & Warehousing Design', prereqs: ['dim-star-schema'], beta: 0.3 },
  { id: 'dim-surrogate-key', label: 'Surrogate vs natural keys',
    section: 'Data Modeling & Warehousing Design', prereqs: ['dim-star-schema'] },
  { id: 'dim-scd-type1', label: 'SCD Type 1 (overwrite)',
    section: 'Data Modeling & Warehousing Design' },
  { id: 'dim-scd-type2', label: 'SCD Type 2 (effective dating, current flag)',
    section: 'Data Modeling & Warehousing Design', prereqs: ['delta-merge'], beta: 0.4 },
  { id: 'dim-scd-type3', label: 'SCD Type 3 (limited history columns)',
    section: 'Data Modeling & Warehousing Design' },
  { id: 'dim-idempotency', label: 'Idempotent pipeline design',
    section: 'Data Modeling & Warehousing Design', beta: 0.3 },
  { id: 'dim-late-arrivals', label: 'Late-arriving data handling',
    section: 'Data Modeling & Warehousing Design', beta: 0.3 },
  { id: 'dim-backfill', label: 'Backfilling historical data',
    section: 'Data Modeling & Warehousing Design' },
  { id: 'dim-data-contracts', label: 'Data contracts & schema agreements',
    section: 'Data Modeling & Warehousing Design' },
  { id: 'dim-delivery-semantics', label: 'At-least-once / at-most-once / exactly-once delivery',
    section: 'Data Modeling & Warehousing Design', beta: 0.3 },
];

/** Map of concept id → Concept for O(1) lookup. */
export const DATABRICKS_CONCEPT_MAP: Record<ConceptId, Concept> = Object.fromEntries(
  DATABRICKS_CONCEPTS.map(c => [c.id, c])
);

/**
 * Databricks tag→concept map. Read by bootstrap-concept-tags.js when invoked
 * with --course=databricks.
 */
export const DATABRICKS_TAG_TO_CONCEPTS: Record<string, ConceptId[]> = {
  // ── Platform / cluster / DBFS ────────────────────────────────────────────
  'fundamentals': ['dbx-architecture'],
  'architecture': ['dbx-architecture'],
  'databricks': ['dbx-architecture'],
  'cluster': ['dbx-cluster-config'],
  'clusters': ['dbx-cluster-config'],
  'all-purpose': ['dbx-cluster-config'],
  'job-cluster': ['dbx-cluster-config'],
  'auto-scaling': ['dbx-cluster-config'],
  'auto-termination': ['dbx-cluster-config'],
  'cost': ['dbx-cluster-config'],
  'policies': ['dbx-cluster-config'],
  'driver': ['dbx-architecture'],
  'execution': ['dbx-architecture'],
  'notebook': ['dbx-architecture'],
  'dbfs': ['dbx-dbfs'],
  'fs': ['dbx-dbfs'],
  'mount': ['dbx-dbfs'],
  'mounts': ['dbx-dbfs'],
  'unmount': ['dbx-dbfs'],
  'list-files': ['dbx-dbfs'],
  'mkdir': ['dbx-dbfs'],
  'dbutils': ['dbx-utilities'],
  'utilities': ['dbx-utilities'],
  'notebook-exit': ['dbx-utilities'],
  'exit': ['dbx-utilities'],
  'secrets': ['dbx-secrets'],
  'widgets': ['dbx-widgets'],
  'parameters': ['dbx-widgets'],
  'dropdown': ['dbx-widgets'],
  'repos': ['dbx-repos'],
  'git': ['dbx-repos'],
  'version-control': ['dbx-repos'],
  'git-operations': ['dbx-repos'],

  // ── Delta Lake ───────────────────────────────────────────────────────────
  'delta': ['delta-acid'],
  'delta-lake': ['delta-acid'],
  'acid': ['delta-acid'],
  'merge': ['delta-merge'],
  'upsert': ['delta-merge'],
  'update': ['delta-merge'],
  'delete': ['delta-merge'],
  'clone': ['delta-clone'],
  'shallow': ['delta-clone'],
  'deep': ['delta-clone'],
  'time-travel': ['delta-time-travel'],
  'versioning': ['delta-time-travel'],
  'restore': ['delta-time-travel'],
  'history': ['delta-time-travel'],
  'optimize': ['delta-optimize'],
  'compaction': ['delta-optimize'],
  'zorder': ['delta-zorder'],
  'vacuum': ['delta-vacuum'],
  'cleanup': ['delta-vacuum'],
  'retention': ['delta-vacuum'],
  'constraint': ['delta-constraints'],
  'check': ['delta-constraints'],
  'not-null': ['delta-constraints'],
  'tblproperties': ['delta-table-properties'],

  // ── PySpark / DataFrame ──────────────────────────────────────────────────
  'spark-session': ['ps-session-init'],
  'entry-point': ['ps-session-init'],
  'initialization': ['ps-session-init'],
  'pyspark': ['ps-session-init'],
  'dataframe': ['ps-dataframe-create'],
  'creation': ['ps-dataframe-create'],
  'create': ['ps-dataframe-create'],
  'create-table': ['ps-dataframe-create'],
  'schema': ['ps-dataframe-create'],
  'structtype': ['ps-dataframe-create'],
  'structfield': ['ps-dataframe-create'],
  'ddl': ['ps-dataframe-create'],
  'printschema': ['ps-dataframe-create'],
  'inspect': ['ps-dataframe-create'],
  'describe': ['ps-dataframe-create'],
  'metadata': ['ps-dataframe-create'],
  'select': ['ps-select-filter'],
  'filter': ['ps-select-filter'],
  'where': ['ps-select-filter'],
  'columns': ['ps-select-filter'],
  'withcolumn': ['ps-with-column'],
  'rename': ['ps-with-column'],
  'lit': ['ps-with-column'],
  'when': ['ps-when-otherwise'],
  'otherwise': ['ps-when-otherwise'],
  'conditional': ['ps-when-otherwise'],
  'cast': ['ps-cast-types'],
  'type-conversion': ['ps-cast-types'],
  'conversion': ['ps-cast-types'],
  'distinct': ['ps-distinct-drop-dup'],
  'deduplication': ['ps-distinct-drop-dup'],
  'dedup': ['ps-distinct-drop-dup'],
  'drop': ['ps-distinct-drop-dup'],
  'orderby': ['ps-orderby-sort'],
  'sort': ['ps-orderby-sort'],
  'limit': ['ps-orderby-sort'],
  'order-by': ['ps-orderby-sort'],
  'groupby': ['ps-groupby-agg'],
  'group-by': ['ps-groupby-agg'],
  'agg': ['ps-groupby-agg'],
  'action': ['ps-actions-vs-transforms'],
  'actions': ['ps-actions-vs-transforms'],
  'lazy': ['ps-actions-vs-transforms'],
  'lazy-evaluation': ['ps-actions-vs-transforms'],
  'transformation': ['ps-actions-vs-transforms'],
  'transformations': ['ps-actions-vs-transforms'],
  'count': ['ps-actions-vs-transforms'],
  'collect': ['ps-actions-vs-transforms'],
  'show': ['ps-actions-vs-transforms'],
  'take': ['ps-actions-vs-transforms'],
  'head': ['ps-actions-vs-transforms'],
  'display': ['ps-actions-vs-transforms'],
  'wide-narrow': ['ps-narrow-vs-wide'],
  'io': ['ps-io-csv'],
  'read': ['ps-io-csv'],
  'csv': ['ps-io-csv'],
  'delimiter': ['ps-io-csv'],
  'corrupt-records': ['ps-io-json'],
  'parse-mode': ['ps-io-json'],
  'json': ['ps-io-json'],
  'parquet': ['ps-io-parquet'],
  'columnar': ['ps-io-parquet'],
  'file-formats': ['ps-io-parquet'],
  'write': ['ps-write-modes'],
  'write-modes': ['ps-write-modes'],
  'append': ['ps-write-modes'],
  'insert': ['ps-write-modes'],
  'string': ['ps-string-fns'],
  'upper': ['ps-string-fns'],
  'lower': ['ps-string-fns'],
  'concat': ['ps-string-fns'],
  'concat_ws': ['ps-string-fns'],
  'substring': ['ps-string-fns'],
  'trim': ['ps-string-fns'],
  'split': ['ps-string-fns'],
  'length': ['ps-string-fns'],
  'formatting': ['ps-string-fns'],
  'regex': ['ps-regex-fns'],
  'regexp_replace': ['ps-regex-fns'],
  'regexp_extract': ['ps-regex-fns'],
  'extract': ['ps-regex-fns'],
  'like': ['ps-regex-fns'],
  'pattern-matching': ['ps-regex-fns'],
  'datetime': ['ps-datetime-fns'],
  'current_date': ['ps-datetime-fns'],
  'current_timestamp': ['ps-datetime-fns'],
  'to_date': ['ps-datetime-fns'],
  'to_timestamp': ['ps-datetime-fns'],
  'date_add': ['ps-datetime-fns'],
  'date_sub': ['ps-datetime-fns'],
  'datediff': ['ps-datetime-fns'],
  'year': ['ps-datetime-fns'],
  'month': ['ps-datetime-fns'],
  'dayofmonth': ['ps-datetime-fns'],
  'date_format': ['ps-datetime-fns'],
  'date': ['ps-datetime-fns'],
  'timestamp': ['ps-datetime-fns'],
  'collection': ['ps-collection-fns'],
  'array': ['ps-collection-fns'],
  'explode': ['ps-collection-fns'],
  'explode_outer': ['ps-collection-fns'],
  'array_contains': ['ps-collection-fns'],
  'array_sort': ['ps-collection-fns'],
  'size': ['ps-collection-fns'],
  'flatten': ['ps-collection-fns'],
  'nested': ['ps-collection-fns'],
  'struct': ['ps-collection-fns'],
  'pivot': ['ps-pivot-unpivot'],
  'unpivot': ['ps-pivot-unpivot'],
  'stack': ['ps-pivot-unpivot'],
  'reshape': ['ps-pivot-unpivot'],
  'wide-format': ['ps-pivot-unpivot'],
  'math': ['ps-math-fns'],
  'round': ['ps-math-fns'],
  'ceil': ['ps-math-fns'],
  'abs': ['ps-math-fns'],
  'sqrt': ['ps-math-fns'],
  'pow': ['ps-math-fns'],
  'greatest': ['ps-math-fns'],
  'aggregate': ['ps-aggregate-fns'],
  'aggregation': ['ps-groupby-agg'],
  'sum': ['ps-aggregate-fns'],
  'max': ['ps-aggregate-fns'],
  'first': ['ps-aggregate-fns'],
  'percentile': ['ps-aggregate-fns'],
  'multiple-aggregations': ['ps-aggregate-fns'],
  'collect_list': ['ps-aggregate-fns'],
  'collect_set': ['ps-aggregate-fns'],
  'null': ['ps-null-handling'],
  'null-handling': ['ps-null-handling'],
  'fillna': ['ps-null-handling'],
  'na': ['ps-null-handling'],
  'coalesce': ['ps-null-handling'],
  'isnull': ['ps-null-handling'],
  'isnotnull': ['ps-null-handling'],
  'three-valued-logic': ['ps-null-handling'],
  'udf': ['ps-udf-pandas-udf'],
  'custom-function': ['ps-udf-pandas-udf'],
  'pandas-udf': ['ps-udf-pandas-udf'],
  'vectorized': ['ps-udf-pandas-udf'],
  'arrow': ['ps-udf-pandas-udf'],

  // ── Spark SQL ────────────────────────────────────────────────────────────
  'temp-view': ['sql-temp-views'],
  'register': ['sql-temp-views'],
  'view': ['sql-temp-views'],
  'show-tables': ['sql-temp-views'],
  'views': ['sql-temp-views'],
  'having': ['sql-where-having'],
  'subquery': ['sql-subqueries'],
  'scalar': ['sql-subqueries'],
  'correlated': ['sql-subqueries'],
  'in': ['sql-subqueries'],
  'not-in': ['sql-subqueries'],
  'exists': ['sql-subqueries'],
  'not-exists': ['sql-subqueries'],
  'derived-table': ['sql-subqueries'],
  'cte': ['sql-cte'],
  'with': ['sql-cte'],
  'case': ['sql-case-expr'],
  'set-operations': ['sql-set-operations'],
  'union': ['sql-set-operations'],
  'union-all': ['sql-set-operations'],
  'intersect': ['sql-set-operations'],
  'except': ['sql-set-operations'],
  'minus': ['sql-set-operations'],
  'join': ['sql-joins-inner-outer'],
  'inner-join': ['sql-joins-inner-outer'],
  'left-join': ['sql-joins-inner-outer'],
  'right-join': ['sql-joins-inner-outer'],
  'full-outer-join': ['sql-joins-inner-outer'],
  'join-types': ['sql-joins-inner-outer'],
  'semi-join': ['sql-joins-semi-anti'],
  'anti-join': ['sql-joins-semi-anti'],
  'left-semi': ['sql-joins-semi-anti'],
  'left-anti': ['sql-joins-semi-anti'],
  'cross-join': ['sql-joins-cross-self'],
  'cartesian': ['sql-joins-cross-self'],
  'self-join': ['sql-joins-cross-self'],
  'window': ['sql-window-ranking'],
  'window-functions': ['sql-window-ranking'],
  'row_number': ['sql-window-ranking'],
  'row-number': ['sql-window-ranking'],
  'rank': ['sql-window-ranking'],
  'dense_rank': ['sql-window-ranking'],
  'dense-rank': ['sql-window-ranking'],
  'ntile': ['sql-window-ranking'],
  'percent-rank': ['sql-window-ranking'],
  'lag': ['sql-window-offset'],
  'lead': ['sql-window-offset'],
  'last': ['sql-window-offset'],
  'window-frame': ['sql-window-frame'],
  'frame': ['sql-window-frame'],
  'rows-between': ['sql-window-frame'],
  'rows': ['sql-window-frame'],
  'running-total': ['sql-window-frame'],
  'moving-average': ['sql-window-frame'],
  'cumulative': ['sql-window-frame'],
  'rollup': ['sql-grouping-rollup'],
  'cube': ['sql-grouping-rollup'],
  'grouping-sets': ['sql-grouping-rollup'],

  // ── Streaming ────────────────────────────────────────────────────────────
  'streaming': ['stream-readstream-writestream'],
  'structured-streaming': ['stream-readstream-writestream'],
  'readstream': ['stream-readstream-writestream'],
  'writestream': ['stream-readstream-writestream'],
  'incremental': ['stream-readstream-writestream'],
  'stream-static': ['stream-readstream-writestream'],
  'trigger': ['stream-triggers'],
  'triggers': ['stream-triggers'],
  'processingtime': ['stream-triggers'],
  'availablenow': ['stream-triggers'],
  'output-modes': ['stream-output-modes'],
  'complete': ['stream-output-modes'],
  'watermark': ['stream-watermarks'],
  'late-data': ['stream-watermarks'],
  'event-time': ['stream-watermarks'],
  'checkpoint': ['stream-checkpoint'],
  'fault-tolerance': ['stream-checkpoint'],
  'exactly-once': ['stream-checkpoint'],
  'recovery': ['stream-checkpoint'],
  'stateful': ['stream-stateful-aggs'],
  'state-management': ['stream-stateful-aggs'],
  'state': ['stream-stateful-aggs'],
  'stream-stream': ['stream-stream-join'],
  'stream-stream-join': ['stream-stream-join'],
  'time-constraint': ['stream-stream-join'],
  'autoloader': ['stream-autoloader'],
  'auto-loader': ['stream-autoloader'],
  'cloudfiles': ['stream-autoloader'],
  'cloud_files': ['stream-autoloader'],
  'ingestion': ['stream-autoloader'],
  'file-detection': ['stream-autoloader'],
  'schema-evolution': ['stream-schema-evolution'],
  'medallion': ['medallion-architecture'],
  'bronze': ['medallion-architecture'],
  'silver': ['medallion-architecture'],
  'gold': ['medallion-architecture'],
  'lakehouse': ['medallion-architecture'],
  'cdc': ['delta-cdf'],
  'change-data-feed': ['delta-cdf'],
  'change-data-capture': ['delta-cdf'],
  'table_changes': ['delta-cdf'],
  'readchangefeed': ['delta-cdf'],
  'change-types': ['delta-cdf'],

  // ── DLT / Workflows ──────────────────────────────────────────────────────
  'dlt': ['dlt-pipeline-basics'],
  'pipeline': ['dlt-pipeline-basics'],
  'streaming-table': ['dlt-pipeline-basics'],
  'materialized-view': ['dlt-pipeline-basics'],
  'expectations': ['dlt-expectations'],
  'expect_or_drop': ['dlt-expectations'],
  'violation-actions': ['dlt-expectations'],
  'data-quality': ['dlt-expectations'],
  'pipeline-mode': ['dlt-pipeline-modes'],
  'continuous': ['dlt-pipeline-modes'],
  'triggered': ['dlt-pipeline-modes'],
  'workflows': ['dbx-workflows'],
  'workflow': ['dbx-workflows'],
  'jobs': ['dbx-workflows'],
  'orchestration': ['dbx-workflows'],
  'task-types': ['dbx-workflows'],
  'failure-handling': ['dbx-workflows'],
  'retry': ['dbx-workflows'],
  'scheduling': ['dbx-workflows'],
  'inter-task': ['dbx-workflows'],
  'task-values': ['dbx-workflows'],
  'taskvalues': ['dbx-workflows'],
  'repair-run': ['dbx-workflows'],
  'failure-recovery': ['dbx-workflows'],
  'dependencies': ['dbx-workflows'],
  'dag': ['dbx-workflows'],

  // ── Optimization ─────────────────────────────────────────────────────────
  'cache': ['ps-cache-persist'],
  'caching': ['ps-cache-persist'],
  'persist': ['ps-cache-persist'],
  'unpersist': ['ps-cache-persist'],
  'storage-level': ['ps-cache-persist'],
  'materialization': ['ps-cache-persist'],
  'memory': ['ps-cache-persist'],
  'broadcast': ['ps-broadcast-join'],
  'shuffle': ['ps-shuffle'],
  'shuffle-partitions': ['ps-shuffle'],
  'parallelism': ['ps-shuffle'],
  'partitioning': ['ps-partitioning'],
  'repartition': ['ps-partitioning'],
  'partitionby': ['ps-partitioning'],
  'aqe': ['ps-aqe'],
  'adaptive': ['ps-aqe'],
  'skew': ['ps-aqe'],
  'spark-ui': ['ps-execution-plans'],
  'monitoring': ['ps-execution-plans'],
  'explain': ['ps-execution-plans'],
  'execution-plan': ['ps-execution-plans'],
  'predicate-pushdown': ['ps-execution-plans'],
  'debugging': ['ps-execution-plans'],
  'partition-pruning': ['ps-partition-pruning'],
  'optimization': ['ps-execution-plans'],
  'performance': ['ps-cache-persist'],

  // ── Governance ───────────────────────────────────────────────────────────
  'governance': ['ucat-grants'],
  'unity-catalog': ['ucat-namespaces'],
  'namespace': ['ucat-namespaces'],
  'catalog': ['ucat-namespaces'],
  'use-catalog': ['ucat-namespaces'],
  'use-schema': ['ucat-namespaces'],
  'managed-table': ['ucat-managed-vs-external'],
  'external-table': ['ucat-managed-vs-external'],
  'grant': ['ucat-grants'],
  'permissions': ['ucat-grants'],
  'all-privileges': ['ucat-grants'],
  'revoke': ['ucat-grants'],
  'show-grants': ['ucat-grants'],
  'lineage': ['ucat-lineage'],
  'audit': ['ucat-lineage'],

  // ── Dimensional modeling ─────────────────────────────────────────────────
  'dimensional-modeling': ['dim-star-schema'],
  'star-schema': ['dim-star-schema'],
  'fact': ['dim-star-schema'],
  'dimension': ['dim-star-schema'],
  'snowflake-schema': ['dim-snowflake-schema'],
  'normalization': ['dim-snowflake-schema'],
  'grain': ['dim-grain'],
  'cardinality': ['dim-grain'],
  'measures': ['dim-additivity'],
  'additivity': ['dim-additivity'],
  'fact-loading': ['dim-additivity'],
  'conformed-dimensions': ['dim-conformed-dims'],
  'enterprise': ['dim-conformed-dims'],
  'bus-matrix': ['dim-conformed-dims'],
  'surrogate-keys': ['dim-surrogate-key'],
  'surrogate-key': ['dim-surrogate-key'],
  'natural-keys': ['dim-surrogate-key'],
  'scd': ['dim-scd-type2'],
  'scd-1': ['dim-scd-type1'],
  'scd-2': ['dim-scd-type2'],
  'type-1': ['dim-scd-type1'],
  'type-2': ['dim-scd-type2'],
  'effective-dating': ['dim-scd-type2'],
  'idempotency': ['dim-idempotency'],
  'pipeline-design': ['dim-idempotency'],
  'late-arriving-data': ['dim-late-arrivals'],
  'backfill': ['dim-backfill'],
  'data-contracts': ['dim-data-contracts'],
  'delivery-semantics': ['dim-delivery-semantics'],
};
