/**
 * Topic.TSQL_STAR_SCHEMA — SQL for Data Engineering (T-SQL).
 * Pillar 5 (Data Modeling): star vs snowflake, conformed dimensions,
 * fact-to-dimension join patterns.
 */
import {
  Question,
  QuestionType,
  Difficulty,
  Topic,
  Course,
  CodeLanguage,
} from '../types';

export const tsql_star_schema_questions: Question[] = [
  {
    id: 'tsql-star-mcq-1',
    type: QuestionType.MULTIPLE_CHOICE,
    difficulty: Difficulty.INTERMEDIATE,
    topic: Topic.TSQL_STAR_SCHEMA,
    course: Course.SQL,
    question: 'What is the defining shape of a star schema?',
    options: [
      { id: 'a', text: 'One central fact table joined directly to a ring of denormalized dimension tables — each dimension is one hop from the fact.', isCorrect: true },
      { id: 'b', text: 'A chain of fact tables each joined to the next, with no dimensions involved.', isCorrect: false },
      { id: 'c', text: 'A single wide table containing every fact and dimension column, with no joins at all.', isCorrect: false },
      { id: 'd', text: 'Many fact tables sharing one giant normalized dimension hierarchy several joins deep.', isCorrect: false },
    ],
    explanation: 'A star = a central fact surrounded by denormalized dimensions, each a single join from the fact. The denormalization (e.g. Category stored on DimProduct, not in a separate DimCategory) keeps queries to one hop per dimension — simple and fast for BI tools.',
    hints: ['Central fact, ring of dimensions', 'Each dimension one join away'],
    tags: ['tsql', 'star-schema', 'dimensional-modeling'],
  },
  {
    id: 'tsql-star-mcq-2',
    type: QuestionType.MULTIPLE_CHOICE,
    difficulty: Difficulty.INTERMEDIATE,
    topic: Topic.TSQL_STAR_SCHEMA,
    course: Course.SQL,
    question: 'How does a snowflake schema differ from a star, and what is the main trade-off?',
    options: [
      { id: 'a', text: 'A snowflake normalizes dimensions into sub-tables (e.g. DimProduct → DimCategory), reducing redundancy but adding extra joins that complicate and slow typical queries.', isCorrect: true },
      { id: 'b', text: 'A snowflake removes all dimensions, so queries hit only the fact table and run faster.', isCorrect: false },
      { id: 'c', text: 'A snowflake merges every dimension into the fact, eliminating joins entirely.', isCorrect: false },
      { id: 'd', text: 'A snowflake and a star are identical; the term just describes a star with more than four dimensions.', isCorrect: false },
    ],
    explanation: 'Snowflaking normalizes a dimension into a hierarchy of sub-tables (DimProduct → DimCategory → DimDepartment). It cuts storage redundancy and centralizes attribute edits, but every extra level is another join, hurting query simplicity and (often) speed. Most warehouses prefer denormalized star dimensions and accept the redundancy.',
    hints: ['Snowflake = normalized dimension hierarchy', 'Less redundancy, more joins'],
    tags: ['tsql', 'star-schema', 'snowflake'],
  },
  {
    id: 'tsql-star-mcq-3',
    type: QuestionType.MULTIPLE_CHOICE,
    difficulty: Difficulty.INTERMEDIATE,
    topic: Topic.TSQL_STAR_SCHEMA,
    course: Course.SQL,
    question: 'What makes a dimension "conformed", and why does it matter?',
    options: [
      { id: 'a', text: 'It is a single shared dimension (e.g. one DimDate or DimCustomer) used identically by multiple fact tables, so metrics from different facts can be compared and combined consistently.', isCorrect: true },
      { id: 'b', text: 'It is a dimension that has been fully normalized to third normal form before loading.', isCorrect: false },
      { id: 'c', text: 'It is a dimension that contains only conformant data types matching the fact table exactly.', isCorrect: false },
      { id: 'd', text: 'It is a dimension automatically generated by the BI tool and never stored in the database.', isCorrect: false },
    ],
    explanation: 'A conformed dimension is shared, with the same keys and meaning, across multiple facts (sales and returns both joining the same DimDate/DimProduct). This is what lets you put metrics from different processes side by side on one row — the backbone of an enterprise bus-matrix design.',
    hints: ['Same dimension shared across multiple facts', 'Enables cross-fact comparison'],
    tags: ['tsql', 'star-schema', 'conformed-dimension'],
  },
  {
    id: 'tsql-star-cloze-1',
    type: QuestionType.CLOZE_CODE,
    difficulty: Difficulty.INTERMEDIATE,
    topic: Topic.TSQL_STAR_SCHEMA,
    course: Course.SQL,
    language: CodeLanguage.SQL,
    question: 'Fill in the join keywords for a star query: total sales amount per product category.',
    template: `SELECT p.Category, SUM(f.Amount) AS TotalSales
FROM dbo.FactSales AS f
___ dbo.DimProduct AS p ___ p.ProductKey = f.ProductKey
GROUP BY p.Category;`,
    blanks: ['JOIN', 'ON'],
    solution: `SELECT p.Category, SUM(f.Amount) AS TotalSales
FROM dbo.FactSales AS f
JOIN dbo.DimProduct AS p ON p.ProductKey = f.ProductKey
GROUP BY p.Category;`,
    blankAlternates: [['INNER JOIN'], []],
    explanation: 'The canonical star query joins the fact to each needed dimension on its surrogate key (`f.ProductKey = p.ProductKey`), then groups by a dimension attribute (`Category`) and aggregates a measure (`SUM(f.Amount)`). One join per dimension — the star\'s whole appeal.',
    hints: ['Fact JOIN dimension', 'Match surrogate keys with ON'],
    tags: ['tsql', 'star-schema', 'join', 'cloze'],
  },
  {
    id: 'tsql-star-1',
    type: QuestionType.CODING,
    difficulty: Difficulty.INTERMEDIATE,
    topic: Topic.TSQL_STAR_SCHEMA,
    course: Course.SQL,
    language: CodeLanguage.SQL,
    question: 'Write a star-schema query: join `dbo.FactSales` (ProductKey, CustomerKey, Amount) to `dbo.DimCustomer` (CustomerKey, Country) and `dbo.DimProduct` (ProductKey, Category), and return Country, Category, and total `Amount` as `TotalSales`, grouped by Country and Category.',
    starterCode: `-- SELECT c.Country, p.Category, SUM(...) FROM dbo.FactSales f JOIN ... JOIN ...
`,
    testCases: [
      {
        input: 'FactSales joined to DimCustomer and DimProduct, grouped by Country, Category',
        expectedOutput: 'Total sales per country and category',
        description: 'Two-dimension star join with aggregation',
      },
    ],
    solution: `SELECT c.Country, p.Category, SUM(f.Amount) AS TotalSales
FROM dbo.FactSales AS f
JOIN dbo.DimCustomer AS c ON c.CustomerKey = f.CustomerKey
JOIN dbo.DimProduct AS p ON p.ProductKey = f.ProductKey
GROUP BY c.Country, p.Category;`,
    explanation: 'A star query fans out from the fact to each dimension it needs on the surrogate keys, then groups by the chosen dimension attributes and sums the measure. Joining two conformed dimensions lets you slice sales by both customer geography and product category in one pass.',
    hints: ['Fact JOIN DimCustomer ON CustomerKey, JOIN DimProduct ON ProductKey', 'GROUP BY c.Country, p.Category; SUM(f.Amount)'],
    tags: ['tsql', 'star-schema', 'join'],
  },
];
