/**
 * Topic.TSQL_INSERT — SQL for Data Engineering (T-SQL).
 * Pillar 6 (ELT & Transformation): INSERT, INSERT … SELECT, SELECT … INTO,
 * the OUTPUT clause.
 */
import {
  Question,
  QuestionType,
  Difficulty,
  Topic,
  Course,
  CodeLanguage,
} from '../types';

export const tsql_insert_questions: Question[] = [
  {
    id: 'tsql-insert-mcq-1',
    type: QuestionType.MULTIPLE_CHOICE,
    difficulty: Difficulty.BEGINNER,
    topic: Topic.TSQL_INSERT,
    course: Course.SQL,
    question: 'In an ELT pipeline, what does `INSERT INTO … SELECT …` let you do that a plain `INSERT … VALUES` cannot?',
    options: [
      { id: 'a', text: 'Load many rows in one set-based statement by selecting them from another table/query — the core move for moving data between staging and target.', isCorrect: true },
      { id: 'b', text: 'Insert a single hard-coded row faster than VALUES can.', isCorrect: false },
      { id: 'c', text: 'Automatically create the target table if it does not exist.', isCorrect: false },
      { id: 'd', text: 'Skip the transaction log so the insert is never rolled back.', isCorrect: false },
    ],
    explanation: '`INSERT … SELECT` is set-based: it loads the entire result of a query in one statement, which is how you move/transform data from staging into a target. `INSERT … VALUES` only supplies literal rows. (To create-and-fill a new table at once, that is `SELECT … INTO`.)',
    hints: ['Loads rows from a query, set-based', 'The staging → target workhorse'],
    tags: ['tsql', 'insert', 'insert-select'],
  },
  {
    id: 'tsql-insert-mcq-2',
    type: QuestionType.MULTIPLE_CHOICE,
    difficulty: Difficulty.INTERMEDIATE,
    topic: Topic.TSQL_INSERT,
    course: Course.SQL,
    question: 'How does `SELECT … INTO NewTable` differ from `INSERT INTO ExistingTable … SELECT`?',
    options: [
      { id: 'a', text: '`SELECT … INTO` creates a brand-new table from the query result; `INSERT … SELECT` loads into a table that must already exist.', isCorrect: true },
      { id: 'b', text: 'They are identical; INTO is just an optional keyword in any INSERT.', isCorrect: false },
      { id: 'c', text: '`SELECT … INTO` requires the target to exist, while `INSERT … SELECT` creates it.', isCorrect: false },
      { id: 'd', text: '`SELECT … INTO` can only copy a single column, while `INSERT … SELECT` copies all columns.', isCorrect: false },
    ],
    explanation: '`SELECT … INTO NewTable FROM …` creates the table on the fly and copies the rows (handy for scratch/staging tables, but it does NOT copy keys/constraints/indexes). `INSERT … SELECT` requires a pre-existing, properly-constrained target — the right choice for loading a real warehouse table.',
    hints: ['INTO = create new table from the query', 'INSERT…SELECT = target must already exist'],
    tags: ['tsql', 'insert', 'select-into'],
  },
  {
    id: 'tsql-insert-cloze-1',
    type: QuestionType.CLOZE_CODE,
    difficulty: Difficulty.BEGINNER,
    topic: Topic.TSQL_INSERT,
    course: Course.SQL,
    language: CodeLanguage.SQL,
    question: 'Fill in the keywords to copy active customers from staging into the dimension.',
    template: `INSERT ___ dbo.DimCustomer (CustomerId, FullName)
___ CustomerId, FullName
FROM stg.Customer
WHERE IsActive = 1;`,
    blanks: ['INTO', 'SELECT'],
    solution: `INSERT INTO dbo.DimCustomer (CustomerId, FullName)
SELECT CustomerId, FullName
FROM stg.Customer
WHERE IsActive = 1;`,
    explanation: '`INSERT INTO target (cols) SELECT … FROM source` loads the query result into an existing table. Always list the target columns explicitly so the load is insulated from column-order changes on either side.',
    hints: ['INSERT INTO target (cols)', 'Source rows come from a SELECT'],
    tags: ['tsql', 'insert', 'insert-select', 'cloze'],
  },
  {
    id: 'tsql-insert-output-cloze-1',
    type: QuestionType.CLOZE_CODE,
    difficulty: Difficulty.INTERMEDIATE,
    topic: Topic.TSQL_INSERT,
    course: Course.SQL,
    language: CodeLanguage.SQL,
    question: 'Fill in the clause that captures the surrogate keys generated by the insert into a table variable.',
    template: `INSERT INTO dbo.DimProduct (ProductCode, ProductName)
___ inserted.ProductKey INTO @NewKeys (ProductKey)
SELECT ProductCode, ProductName
FROM stg.Product;`,
    blanks: ['OUTPUT'],
    solution: `INSERT INTO dbo.DimProduct (ProductCode, ProductName)
OUTPUT inserted.ProductKey INTO @NewKeys (ProductKey)
SELECT ProductCode, ProductName
FROM stg.Product;`,
    explanation: 'The `OUTPUT` clause exposes the `inserted` (and for updates/deletes, `deleted`) pseudo-tables, so you can capture auto-generated values like IDENTITY surrogate keys as part of the same statement — essential when a later load step needs the keys just created.',
    hints: ['The clause exposing the inserted pseudo-table', 'OUTPUT inserted.<col> INTO …'],
    tags: ['tsql', 'insert', 'output-clause', 'cloze'],
  },
  {
    id: 'tsql-insert-1',
    type: QuestionType.CODING,
    difficulty: Difficulty.INTERMEDIATE,
    topic: Topic.TSQL_INSERT,
    course: Course.SQL,
    language: CodeLanguage.SQL,
    question: 'Load `dbo.FactSales (CustomerKey, ProductKey, Amount)` from `stg.Sales (CustomerId, ProductCode, Amount)`, resolving the natural keys to surrogate keys by joining `dbo.DimCustomer (CustomerKey, CustomerId)` and `dbo.DimProduct (ProductKey, ProductCode)`. Use INSERT … SELECT.',
    starterCode: `-- INSERT INTO dbo.FactSales (...) SELECT ... FROM stg.Sales s JOIN ... JOIN ...
`,
    testCases: [
      {
        input: 'INSERT INTO FactSales SELECT surrogate keys by joining staging to both dimensions',
        expectedOutput: 'Fact loaded with surrogate keys resolved from natural keys',
        description: 'Surrogate-key lookup load via INSERT…SELECT',
      },
    ],
    solution: `INSERT INTO dbo.FactSales (CustomerKey, ProductKey, Amount)
SELECT c.CustomerKey, p.ProductKey, s.Amount
FROM stg.Sales AS s
JOIN dbo.DimCustomer AS c ON c.CustomerId = s.CustomerId
JOIN dbo.DimProduct AS p ON p.ProductCode = s.ProductCode;`,
    explanation: 'This is the canonical fact load: the staging rows carry natural keys (`CustomerId`, `ProductCode`), so you join to each dimension to translate them into the warehouse surrogate keys (`CustomerKey`, `ProductKey`) before inserting. The fact stores surrogates, never the source business keys.',
    hints: ['JOIN staging to each dimension on the natural key', 'SELECT the surrogate keys + measure into the fact'],
    tags: ['tsql', 'insert', 'insert-select', 'surrogate-keys'],
  },
];
