/**
 * Topic.DJ_FACTORY_BOY — all question types for this topic.
 * Auto-consolidated by scripts/consolidate-by-topic.js from:
 *   backendAdvancedPedagogyQuestions.ts (1), backendInfraQuestions.ts (4), djangoBatchDExpansionQuestions.ts (6)
 */
import {
  Question,
  QuestionType,
  Difficulty,
  Topic,
  Course,
  CodeLanguage,
} from '../types';

export const dj_factory_boy_questions: Question[] = [
  {
      id: 'dj-factoryboy-cloze-1',
      type: QuestionType.CLOZE_CODE,
      difficulty: Difficulty.INTERMEDIATE,
      topic: Topic.DJ_FACTORY_BOY,
      course: Course.BACKEND,
      language: CodeLanguage.PYTHON,
      question: 'Build a factory_boy factory for Article: deterministic title sequence, faker body, FK to UserFactory.',
      template: `import factory
from articles.models import Article

class ArticleFactory(factory.django.___):
    class Meta:
        model = Article

    title = factory.___(lambda n: f"Article {n}")
    body = factory.Faker("paragraph")
    author = factory.___(UserFactory)`,
      blanks: ['DjangoModelFactory', 'Sequence', 'SubFactory'],
      solution: 'import factory\nfrom articles.models import Article\n\nclass ArticleFactory(factory.django.DjangoModelFactory):\n    class Meta:\n        model = Article\n\n    title = factory.Sequence(lambda n: f"Article {n}")\n    body = factory.Faker("paragraph")\n    author = factory.SubFactory(UserFactory)',
      explanation: '`DjangoModelFactory` uses `Meta.model` and saves to the DB by default. `Sequence` produces unique deterministic values keyed off an incrementing `n`. `Faker` generates plausible random data. `SubFactory` builds related instances on demand — eliminating manual FK setup in tests.',
      hints: ['DjangoModelFactory for Django models', 'Sequence(lambda n: ...) for uniqueness', 'SubFactory for FK relations'],
      tags: ['django', 'factory_boy', 'testing', 'cloze', 'Sequence', 'Faker', 'SubFactory'],
      concepts: ['py-test-isolation'],
    },
  {
      id: 'py-dj-factory-what',
      type: QuestionType.MULTIPLE_CHOICE,
      difficulty: Difficulty.BEGINNER,
      topic: Topic.DJ_FACTORY_BOY,
      course: Course.BACKEND,
      question: 'What problem does factory_boy solve in Django tests?',
      options: [
        { id: 'a', text: 'It compiles test modules to C so large Django suites run faster without changing any of the test code you have already written', isCorrect: false },
        { id: 'b', text: 'Mocking HTTP calls to external services so tests never hit real APIs — it records responses once and replays them on later runs', isCorrect: false },
        { id: 'c', text: 'Static type checking for model fields, catching mismatched attribute types in tests before they ever reach the database layer', isCorrect: false },
        { id: 'd', text: 'Generating test data concisely — `UserFactory()` fills sensible defaults so each test overrides only the fields it actually cares about', isCorrect: true },
      ],
      explanation: 'Without factories: every test repeats long model-creation boilerplate AND creates fragile coupling — adding a required field to `User` breaks all tests that create users. With `factory_boy`: add the default to `UserFactory`, every test keeps working. Defaults are filled intelligently — Faker-generated values, unique sequenced usernames, sensible timestamps. Pair with `pytest-factoryboy` for automatic fixture registration. Alternative: Django fixtures (JSON dumps) — brittle, global, hard to update — factories win.',
      hints: [
        'Generates realistic test data with sensible defaults',
        'Tests override only the fields they care about',
        'Adding required model fields → update the factory once',
      ],
      tags: ['django', 'testing', 'factory_boy'],
      concepts: ['py-test-isolation'],
    },
  {
      id: 'py-dj-factory-userfactory',
      type: QuestionType.CODING,
      difficulty: Difficulty.BEGINNER,
      topic: Topic.DJ_FACTORY_BOY,
      course: Course.BACKEND,
      language: CodeLanguage.PYTHON,
      question: 'Write a simple `UserFactory`. Import `factory` and the Django `User` model. Define a `UserFactory` class that subclasses `factory.django.DjangoModelFactory`. Give it an inner `Meta` class whose `model` attribute is `User`. Add a `username` field generated with `factory.Sequence` that produces unique strings of the form `"user_0"`, `"user_1"`, and so on, and an `email` field generated with `factory.Faker` using the `"email"` provider for realistic addresses. Callers will either invoke it with no arguments or override fields like `username="alice"`.',
      starterCode: `# Write UserFactory(factory.django.DjangoModelFactory): inner Meta with
# model = User; a username generated by factory.Sequence as "user_0",
# "user_1", ...; an email generated by factory.Faker("email").
`,
      testCases: [
        {
          input: 'basic DjangoModelFactory',
          expectedOutput: 'UserFactory() creates a User with unique username + fake email',
          description: 'Meta.model + field generators',
        },
      ],
      solution: `import factory
from django.contrib.auth.models import User

class UserFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = User

    username = factory.Sequence(lambda n: f"user_{n}")
    email = factory.Faker("email")`,
      explanation: 'Generators: `Sequence` increments `n` per call (unique strings), `Faker("email")` / `Faker("name")` / `Faker("sentence")` produce realistic fake data, `LazyAttribute(lambda o: f"{o.first_name.lower()}@example.com")` derives from other fields, `FuzzyChoice([...])` picks random from a list. `.build()` creates UNsaved, `.create()` (default) calls `.objects.create()`. Bulk: `UserFactory.create_batch(10)`.',
      tieredHints: {
        apiSignature: 'factory.Sequence(func) -> Any',
        skeleton: 'import factory\nfrom django.contrib.auth.models import ____\n\nclass ____(factory.django.____):\n    class ____:\n        ____ = ____\n\n    ____ = factory.____(lambda n: f"user_{n}")\n    ____ = factory.____("email")',
      },
      hints: [
        'Sequence for unique integers / strings',
        'Faker for realistic names / emails / addresses',
        '.build() without save(), .create() with save(), .create_batch(N) for bulk',
      ],
      tags: ['django', 'factory_boy', 'Sequence', 'Faker'],
      concepts: ['dj-test-fixtures'],
    },
  {
      id: 'py-dj-factory-subfactory',
      type: QuestionType.CODING,
      difficulty: Difficulty.BEGINNER,
      topic: Topic.DJ_FACTORY_BOY,
      course: Course.BACKEND,
      language: CodeLanguage.PYTHON,
      question: 'Use `SubFactory` for foreign-key relations. Given that `Post.author` is a `ForeignKey` to `User`, define a `PostFactory` class that subclasses `factory.django.DjangoModelFactory` and has an inner `Meta` pointing at the `Post` model. Give it a `title` field generated via `factory.Faker` with the `"sentence"` provider, and an `author` field generated via `factory.SubFactory` referencing `UserFactory`. Now a caller invoking the factory with no arguments gets a Post AND its author; passing `author=existing_user` reuses an existing user.',
      starterCode: `# Write PostFactory(factory.django.DjangoModelFactory): inner Meta with
# model = Post; a title via factory.Faker("sentence"); an author via
# factory.SubFactory(UserFactory) so each Post brings its own User.
`,
      testCases: [
        {
          input: 'SubFactory for FK',
          expectedOutput: 'PostFactory() creates Post + cascading User',
          description: 'SubFactory nests factories for relations',
        },
      ],
      solution: `import factory
from .factories import UserFactory
from .models import Post

class PostFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = Post

    title = factory.Faker("sentence")
    author = factory.SubFactory(UserFactory)`,
      explanation: 'SubFactory calls the referenced factory\'s `.create()` for each new Post. Nest arbitrarily deep (Comment → Post → Author). For self-referential / recursive FKs, use `factory.RelatedFactory` (post-save hook). For M2M: `@factory.post_generation def tags(self, create, extracted, **kwargs): if extracted: self.tags.set(extracted)`. Now `PostFactory(tags=[tag1, tag2])` sets the M2M after the Post is saved.',
      tieredHints: {
        apiSignature: 'factory.SubFactory(factory_class, **kwargs)',
        skeleton: 'import factory\nfrom .factories import ____\nfrom .models import ____\n\nclass ____(factory.django.____):\n    class ____:\n        ____ = ____\n\n    ____ = factory.____("sentence")\n    ____ = factory.____(____)',
      },
      hints: [
        'SubFactory for FK / OneToOne relations',
        'RelatedFactory for reverse relations / self-references',
        'post_generation hook for M2M',
      ],
      tags: ['django', 'factory_boy', 'SubFactory', 'foreign-key'],
      concepts: ['dj-test-fixtures'],
    },
  {
      id: 'dj-factoryboy-trait-cloze-1',
      type: QuestionType.CLOZE_CODE,
      difficulty: Difficulty.BEGINNER,
      topic: Topic.DJ_FACTORY_BOY,
      course: Course.BACKEND,
      language: CodeLanguage.PYTHON,
      question: 'Fill in the inner class that groups named variations and the helper that bundles field overrides under one name.',
      template: `class UserFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = User

    class ___:
        admin = factory.___(is_staff=True, is_superuser=True)`,
      blanks: ['Params', 'Trait'],
      solution: 'class UserFactory(factory.django.DjangoModelFactory):\n    class Meta:\n        model = User\n\n    class Params:\n        admin = factory.Trait(is_staff=True, is_superuser=True)',
      explanation: '`class Params:` is the inner class that holds trait declarations. `factory.Trait(...)` bundles a set of field overrides under one name — activate it with `UserFactory(admin=True)`.',
      hints: ['Inner class name for trait declarations', 'Helper that bundles field overrides'],
      tags: ['django', 'factory_boy', 'Trait', 'cloze'],
      concepts: ['dj-test-fixtures'],
    },
  {
      id: 'py-dj-factory-traits',
      type: QuestionType.CODING,
      difficulty: Difficulty.BEGINNER,
      topic: Topic.DJ_FACTORY_BOY,
      course: Course.BACKEND,
      language: CodeLanguage.PYTHON,
      question: 'Use `Trait` for named variations. Extend `UserFactory` (whose `Meta.model` is `User`) by adding an inner `Params` class. Inside `Params`, declare a trait named `admin` built from `factory.Trait` that, when activated, sets `is_staff` and `is_superuser` to True. Now callers passing `admin=True` get a staff+superuser; without it they get a normal user.',
      starterCode: `# Extend UserFactory with an inner Params class declaring an \`admin\`
# trait (factory.Trait) that sets is_staff and is_superuser to True.
`,
      testCases: [
        {
          input: 'Trait for named variation',
          expectedOutput: 'UserFactory(admin=True) → is_staff=True, is_superuser=True',
          description: 'Traits bundle field overrides under a name',
        },
      ],
      solution: `import factory
from django.contrib.auth.models import User

class UserFactory(factory.django.DjangoModelFactory):
    class Meta:
        model = User

    username = factory.Sequence(lambda n: f"user_{n}")
    email = factory.Faker("email")

    class Params:
        admin = factory.Trait(is_staff=True, is_superuser=True)`,
      explanation: 'Traits avoid "multiple factory subclasses for every variation" bloat. Combine multiple: `UserFactory(admin=True, verified=True)`. For flows that need a truly different factory (different model), subclass: `class AdminUserFactory(UserFactory): is_staff = True`. Rule of thumb: Trait for field-level flags that apply to the same model; subclass for "structurally different" factories (e.g. Comment on Post vs Comment on Photo).',
      tieredHints: {
        apiSignature: 'factory.Trait(**kwargs)',
        skeleton: 'import factory\nfrom django.contrib.auth.models import ____\n\nclass ____(factory.django.____):\n    class ____:\n        ____ = ____\n\n    ____ = factory.____(lambda n: f"user_{n}")\n    ____ = factory.____("email")\n\n    class ____:\n        ____ = factory.____(is_staff=True, is_superuser=True)',
      },
      hints: [
        'class Params: trait_name = Trait(field_overrides)',
        'Activate: Factory(trait_name=True)',
        'Subclass when the structure differs, not just field values',
      ],
      tags: ['django', 'factory_boy', 'Trait'],
      concepts: ['dj-test-fixtures'],
    },
  {
      id: 'dj-factoryboy-batch-cloze-1',
      type: QuestionType.CLOZE_CODE,
      difficulty: Difficulty.BEGINNER,
      topic: Topic.DJ_FACTORY_BOY,
      course: Course.BACKEND,
      language: CodeLanguage.PYTHON,
      question: 'Fill in the factory method that creates several instances at once, with per-batch field overrides.',
      template: `published = PostFactory.___(3, is_published=True)
drafts = PostFactory.___(2, is_published=False)`,
      blanks: ['create_batch', 'create_batch'],
      solution: 'published = PostFactory.create_batch(3, is_published=True)\ndrafts = PostFactory.create_batch(2, is_published=False)',
      explanation: '`create_batch(N, **overrides)` calls `.create()` N times, applying the same overrides to each. Different calls can pass different overrides, letting one arrange step build several distinct groups of test data.',
      hints: ['Factory method name: create + batch'],
      tags: ['django', 'factory_boy', 'create_batch', 'cloze'],
      concepts: ['dj-test-fixtures'],
    },
  {
      id: 'py-dj-factory-usage-test',
      type: QuestionType.CODING,
      difficulty: Difficulty.BEGINNER,
      topic: Topic.DJ_FACTORY_BOY,
      course: Course.BACKEND,
      language: CodeLanguage.PYTHON,
      question: 'Use a factory in a Django test. Import `TestCase` and `PostFactory`. Define a `PostListTest` class that subclasses `TestCase`, with a test method `test_lists_only_published`. Arrange: use `PostFactory.create_batch` twice — three posts with `is_published=True`, and two posts with `is_published=False`. Act: issue a GET to the path `"/posts/"` via `self.client`. Assert that the `posts` entry in the response context has a count of `3`. Factories make the "arrange" step of AAA tests readable.',
      starterCode: `# Write PostListTest(TestCase).test_lists_only_published: create_batch 3
# posts is_published=True and 2 is_published=False, GET "/posts/" via
# self.client, and assert response.context["posts"] has a count of 3.
`,
      testCases: [
        {
          input: 'factory_boy inside a TestCase',
          expectedOutput: 'Arrange 5 posts, assert only 3 shown',
          description: 'create_batch for bulk + kwarg overrides per batch',
        },
      ],
      solution: `from django.test import TestCase
from .factories import PostFactory

class PostListTest(TestCase):
    def test_lists_only_published(self):
        PostFactory.create_batch(3, is_published=True)
        PostFactory.create_batch(2, is_published=False)
        response = self.client.get("/posts/")
        self.assertEqual(response.context["posts"].count(), 3)`,
      explanation: '`create_batch(N, **kwargs)` calls `.create()` N times with the overrides. `Post.objects.all().count()` would be 5, but the view filters to published — test proves the filter works. Factories make tests self-documenting: the test function\'s first 2 lines READ as "given 3 published and 2 draft posts". `pytest-django` + `pytest-factoryboy` lets you use factories as pytest fixtures directly.',
      tieredHints: {
        apiSignature: 'Factory.create_batch(size, **kwargs)',
        skeleton: 'from django.test import TestCase\nfrom .factories import ____\n\nclass ____(____):\n    def ____(self):\n        ____.____(3, is_published=True)\n        ____.____(2, is_published=False)\n        response = self.client.____("/posts/")\n        self.____(response.context["posts"].____(), 3)',
      },
      hints: [
        'create_batch(N, **overrides) for bulk',
        'Each batch can have different overrides',
        'pytest-factoryboy auto-generates fixtures from factories',
      ],
      tags: ['django', 'factory_boy', 'TestCase', 'create_batch'],
      concepts: ['dj-test-fixtures'],
    },
  {
      id: 'py-dj-factory-vs-fixture',
      type: QuestionType.MULTIPLE_CHOICE,
      difficulty: Difficulty.INTERMEDIATE,
      topic: Topic.DJ_FACTORY_BOY,
      course: Course.BACKEND,
      question: 'Why prefer factories over Django\'s JSON fixtures or per-test `setUp()` for test data?',
      options: [
        { id: 'a', text: 'Factories are local to tests, composable via SubFactory, resilient to schema changes, and generate realistic Faker data — fixtures are global and brittle', isCorrect: true },
        { id: 'b', text: 'Django deprecated JSON fixtures in 4.0, so loaddata only works on legacy projects and factories are the only supported replacement', isCorrect: false },
        { id: 'c', text: 'Fixtures are always slower because every fixture row is re-inserted before each individual test method, while factories insert once per class', isCorrect: false },
        { id: 'd', text: 'setUp() no longer exists on modern Django TestCase classes — it was replaced by factories and the setUpTestData hook in Django 5', isCorrect: false },
      ],
      explanation: 'Three choices: (1) JSON fixtures — loaded at class/session start, shared globally, brittle to schema changes, values not self-describing. (2) `setUp` — local and readable but copy-pasted across files, breaks on required-field additions. (3) factories — shared definitions, overridable per test, Faker-generated realistic values. Factory+trait combos are the pattern modern Django teams default to.',
      hints: [
        'Factories: local, composable, schema-resilient',
        'JSON fixtures: global, brittle, no semantics',
        'setUp: local but duplicated across tests',
      ],
      tags: ['django', 'factory_boy', 'fixtures', 'testing'],
      concepts: ['py-test-isolation'],
    },
];
